#include "../src/services/geometry/fit/RoundTechnicCalibrationArtifact.h"
#include "../src/services/geometry/ThreeMfWriter.h"
#include "../src/services/geometry/LDrawLibraryService.h"
#include "../src/services/geometry/print/LDrawPrintGeometryBuilder.h"
#include "../src/services/geometry/print/PrintMeshAnalysis.h"

#include <QCoreApplication>
#include <QDir>
#include <QFile>
#include <QJsonDocument>
#include <QJsonArray>
#include <QSaveFile>
#include <QTextStream>

#include <cmath>

using namespace PrintGeometry;
namespace {
bool require(bool value,const QString&message){if(!value)QTextStream(stderr)<<"FAIL: "<<message<<Qt::endl;return value;}
FunctionalFeature fixture(){FunctionalFeature f;f.stableIdentity="fixture";f.family=FunctionalInterfaceFamily::RoundTechnicPassage;f.role=FunctionalInterfaceRole::Female;f.materialSide=FunctionalMaterialSide::EmptyInsideMaterialOutside;f.eligibility=FunctionalEligibility::Eligible;f.confidence=SemanticConfidence::HighConfidence;f.frame={{0,0,0},{0,1,0},{1,0,0},{0,0,-1},false};f.nominalRadiusMillimetres=2.40006;f.nominalDiameterMillimetres=4.80012;f.nominalAxialExtentMillimetres=8;f.nominalEngagementExtentMillimetres=6.4;f.radialProfile={{-4.1,3.20008},{-3.2,3.20008},{-3.2,2.40006},{3.2,2.40006},{3.2,3.20008},{4.1,3.20008}};f.operandAction=FunctionalOperandAction::Subtract;f.constructionRecipe="round-through-passage-v1";f.governingOperandIdentity="fixture:operand";f.evidenceContract="official-ldraw-peghole-pair-v1";return f;}
bool sameMesh(const PrintMesh&a,const PrintMesh&b){if(a.faces!=b.faces||a.vertices.size()!=b.vertices.size())return false;for(std::size_t i=0;i<a.vertices.size();++i)if(a.vertices[i].x!=b.vertices[i].x||a.vertices[i].y!=b.vertices[i].y||a.vertices[i].z!=b.vertices[i].z)return false;return true;}
}

int main(int argc,char**argv){QCoreApplication app(argc,argv);bool ok=true;const auto artifact=RoundTechnicCalibrationArtifact::generate(fixture());ok&=require(artifact.ok,"synthetic calibration artifact generation");ok&=require(artifact.artifactIdentity=="round-technic-female-horizontal-v1"&&artifact.orientationIdentity=="flat-base-horizontal-axis-y-v1","versioned artifact and orientation identity");ok&=require(artifact.candidates.size()==7,"seven independent candidates");const auto expected=RoundTechnicCalibrationArtifact::diameterCorrectionsMillimetres();for(int i=0;i<expected.size();++i){ok&=require(std::abs(artifact.candidates[i].diameterCorrectionMillimetres-expected[i])<1e-12,"ordered correction map");ok&=require(std::abs(artifact.candidates[i].functionalDiameterMillimetres-(4.80012+expected[i]))<1e-9,"actual candidate diameter");}ok&=require(artifact.analysis.connectedComponents==1&&artifact.analysis.boundaryEdges==0&&artifact.analysis.nonManifoldEdges==0&&artifact.analysis.nonManifoldVertices==0&&artifact.analysis.selfIntersections==0,"printable topology");const auto bounds=artifact.analysis.bounds;ok&=require(std::abs((bounds.maximum.x-bounds.minimum.x)-92.0)<1e-6&&std::abs((bounds.maximum.y-bounds.minimum.y)-8.0)<1e-6&&std::abs((bounds.maximum.z-bounds.minimum.z)-14.0)<1e-6,"artifact dimensions");const auto repeated=RoundTechnicCalibrationArtifact::generate(fixture());ok&=require(repeated.ok&&sameMesh(repeated.mesh,artifact.mesh),"deterministic generation");
    auto experiment=RoundTechnicCalibrationArtifact::observationTemplate(artifact);experiment.process.printerIdentity="Test Printer";experiment.process.materialIdentity="Test PLA";experiment.process.profileName="0.20 Standard";experiment.process.hasNozzleDiameter=true;experiment.process.nozzleDiameterMillimetres=.4;experiment.process.hasLayerHeight=true;experiment.process.layerHeightMillimetres=.2;experiment.process.actualPrintedOrientation=FitPrintedOrientation::FeatureAxisParallelToBuildPlate;experiment.performedUtc=QDateTime::fromString("2026-09-20T12:00:00.000Z",Qt::ISODateWithMs);FitCalibrationObservation first;first.result=FitObservation::Preferred;first.repeatNumber=1;first.notes="physical mate";first.performedUtc=experiment.performedUtc;QString error;ok&=require(FitCalibrationEvidencePolicy::addObservation(&experiment,3,first,&error),"first physical observation accepted");auto repeat=first;repeat.repeatNumber=2;ok&=require(FitCalibrationEvidencePolicy::addObservation(&experiment,3,repeat,&error)&&experiment.candidates[2].observations.size()==2,"multiple observations retained");ok&=require(!FitCalibrationEvidencePolicy::addObservation(&experiment,3,repeat,&error),"ambiguous duplicate repeat rejected");ok&=require(FitCalibrationEvidencePolicy::selectPreferredCandidate(&experiment,3,&error)&&experiment.state==FitEvidenceState::CandidateSelected,"provisional preferred candidate selected");ok&=require(!FitCalibrationEvidencePolicy::markVerified(&experiment,&error),"first-pass artifact cannot become verified");const auto json=FitCalibrationExperimentJson::toJson(experiment);FitCalibrationExperiment decoded;ok&=require(FitCalibrationExperimentJson::fromJson(json,&decoded,&error)&&decoded.artifactIdentity==experiment.artifactIdentity&&decoded.candidates.size()==7&&decoded.candidates[2].observations.size()==2&&decoded.preferredCandidateIndex==3&&decoded.process.actualPrintedOrientation==FitPrintedOrientation::FeatureAxisParallelToBuildPlate&&decoded.process.profileName=="0.20 Standard"&&decoded.hasRegenerationPrototype,"versioned observation JSON round trip");QJsonObject invalid;ok&=require(!FitCalibrationExperimentJson::fromJson(invalid,&decoded,&error),"invalid observation document rejected");

    RoundTechnicCalibrationArtifactDefinition fine;fine.artifactIdentity="round-technic-female-horizontal-verification-v2";fine.parentArtifactIdentity=artifact.artifactIdentity;fine.centerDiameterCorrectionMillimetres=.10;fine.candidateSpacingMillimetres=.025;fine.candidateCount=5;const auto fineArtifact=RoundTechnicCalibrationArtifact::generate(decoded.regenerationPrototype,fine);ok&=require(fineArtifact.ok&&fineArtifact.candidates.size()==5,"fine-search artifact generated");for(int i=0;i<5;++i)ok&=require(std::abs(fineArtifact.candidates[i].diameterCorrectionMillimetres-(.05+.025*i))<1e-9,"arbitrary fine-search center and spacing");ok&=require(fineArtifact.analysis.connectedComponents==1&&fineArtifact.analysis.boundaryEdges==0&&fineArtifact.analysis.nonManifoldEdges==0&&fineArtifact.analysis.selfIntersections==0,"fine-search topology");ok&=require(std::abs((fineArtifact.analysis.bounds.maximum.x-fineArtifact.analysis.bounds.minimum.x)-68.0)<1e-6,"fine-search remains 100 percent physical size");const auto fineRepeated=RoundTechnicCalibrationArtifact::generate(decoded.regenerationPrototype,fine);ok&=require(fineRepeated.ok&&sameMesh(fineRepeated.mesh,fineArtifact.mesh),"fine-search generation deterministic");auto verification=RoundTechnicCalibrationArtifact::observationTemplate(fineArtifact,fine);verification.process=experiment.process;for(int candidateIndex:{2,3,4}){FitCalibrationObservation observation=first;observation.repeatNumber=1;observation.result=candidateIndex==3?FitObservation::Preferred:FitObservation::Acceptable;ok&=require(FitCalibrationEvidencePolicy::addObservation(&verification,candidateIndex,observation,&error),"verification comparison observation");if(candidateIndex==3){observation.repeatNumber=2;ok&=require(FitCalibrationEvidencePolicy::addObservation(&verification,candidateIndex,observation,&error),"verification repeat observation");}}ok&=require(FitCalibrationEvidencePolicy::selectPreferredCandidate(&verification,3,&error)&&FitCalibrationEvidencePolicy::markVerified(&verification,&error)&&verification.state==FitEvidenceState::Verified,"repeat plus adjacent evidence becomes verified");FitCalibrationEvidencePolicy::markStaleIfArtifactChanged(&verification,"round-technic-female-horizontal-verification-v3");ok&=require(verification.state==FitEvidenceState::Stale,"artifact version mismatch marks evidence stale");RoundTechnicCalibrationArtifactDefinition invalidFine=fine;invalidFine.candidateCount=4;ok&=require(!RoundTechnicCalibrationArtifact::generate(decoded.regenerationPrototype,invalidFine).ok,"ambiguous even candidate range rejected");
    const auto args=app.arguments();const int libraryAt=args.indexOf("--ldraw"),outputAt=args.indexOf("--output");if(libraryAt>=0&&libraryAt+1<args.size()){const auto loaded=LDrawLibraryService::loadPart(args[libraryAt+1],"3700");ok&=require(loaded.ok(),"real 3700 contract load");const auto semantic=LDrawSemanticOperandBuilder::build(loaded);const FunctionalFeature*feature=nullptr;for(const auto&operand:semantic.operands)if(!operand.functionalFeatures.isEmpty()){feature=&operand.functionalFeatures.front();break;}ok&=require(feature,"real retained functional contract");if(feature){const auto real=RoundTechnicCalibrationArtifact::generate(*feature);ok&=require(real.ok,"real-contract artifact generation");ok&=require(real.analysis.connectedComponents==1&&real.analysis.boundaryEdges==0&&real.analysis.nonManifoldEdges==0&&real.analysis.nonManifoldVertices==0&&real.analysis.selfIntersections==0,"real retained contract produces validated artifact topology");for(int i=0;i<real.candidates.size();++i)ok&=require(std::abs(real.candidates[i].functionalDiameterMillimetres-(feature->nominalDiameterMillimetres+expected[i]))<1e-9,"real contract drives candidate dimensions");if(outputAt>=0&&outputAt+1<args.size()){QDir output(args[outputAt+1]);ok&=require(output.mkpath("."),"artifact output directory");const auto modelPath=output.filePath("BrickSuite-round-technic-female-horizontal-v1.3mf");ThreeMfWriter::Options options;options.uniformScale=1.0;options.objectName="BrickSuite Round Technic Female Calibration v1";options.partIdentity=real.artifactIdentity;options.modelColor=QColor("#0055BF");ok&=require(ThreeMfWriter::write(real.mesh,modelPath,options,&error),QStringLiteral("3MF export: %1").arg(error));auto sheet=RoundTechnicCalibrationArtifact::observationTemplate(real);QSaveFile file(output.filePath("BrickSuite-round-technic-female-horizontal-v1-observations.json"));ok&=require(file.open(QIODevice::WriteOnly)&&file.write(QJsonDocument(FitCalibrationExperimentJson::toJson(sheet)).toJson(QJsonDocument::Indented))>0&&file.commit(),"observation template export");QTextStream(stdout)<<"artifact="<<modelPath<<Qt::endl<<"observations="<<output.filePath("BrickSuite-round-technic-female-horizontal-v1-observations.json")<<Qt::endl;}}}
    auto child=RoundTechnicCalibrationArtifact::observationTemplate(fineArtifact,fine);child.process=experiment.process;ok&=require(child.parentArtifactIdentity==artifact.artifactIdentity&&std::abs(child.centerDiameterCorrectionMillimetres-.10)<1e-12,"fine-search child retains parent identity and selected correction");ok&=require(child.process.printerIdentity==experiment.process.printerIdentity&&child.process.materialIdentity==experiment.process.materialIdentity&&child.process.nozzleDiameterMillimetres==experiment.process.nozzleDiameterMillimetres&&child.process.profileName==experiment.process.profileName&&child.process.layerHeightMillimetres==experiment.process.layerHeightMillimetres&&child.process.actualPrintedOrientation==experiment.process.actualPrintedOrientation&&child.process.orientationNotes==experiment.process.orientationNotes&&child.process.dimensionalCompensationNotes==experiment.process.dimensionalCompensationNotes,"fine-search child inherits manufacturing context");bool childHasObservations=false;for(const auto&candidate:child.candidates)childHasObservations|=!candidate.observations.isEmpty();ok&=require(!childHasObservations&&child.preferredCandidateIndex==0&&child.state==FitEvidenceState::Draft,"fine-search child starts with new unevaluated evidence");
    FitCalibrationSession session;session.sessionIdentity="round-technic-session-1";session.process=experiment.process;session.hasCoarseExperiment=true;session.coarseExperiment=experiment;session.hasFineExperiment=true;session.fineExperiment=child;const auto sessionJson=FitCalibrationSessionJson::toJson(session);FitCalibrationSession decodedSession;ok&=require(sessionJson.value("formatVersion").toInt()==3&&FitCalibrationSessionJson::fromJson(sessionJson,&decodedSession,&error),"unified calibration session round trip");ok&=require(decodedSession.hasCoarseExperiment&&decodedSession.hasFineExperiment&&decodedSession.coarseExperiment.candidates[2].observations.size()==2&&decodedSession.fineExperiment.candidates[0].observations.isEmpty(),"coarse and fine evidence remain independent");ok&=require(decodedSession.coarseExperiment.preferredCandidateIndex==3&&decodedSession.fineExperiment.preferredCandidateIndex==0&&decodedSession.process.printerIdentity==experiment.process.printerIdentity&&decodedSession.fineExperiment.parentArtifactIdentity==artifact.artifactIdentity,"session preserves independent selections, shared process, and lineage");FitCalibrationSession coarseOnly;ok&=require(FitCalibrationSessionJson::fromJson(json,&coarseOnly,&error)&&coarseOnly.hasCoarseExperiment&&!coarseOnly.hasFineExperiment&&coarseOnly.coarseExperiment.candidates[2].observations.size()==2,"legacy v2 coarse experiment upgrades without observation loss");const auto legacyChildJson=FitCalibrationExperimentJson::toJson(child);FitCalibrationSession fineOnly;ok&=require(FitCalibrationSessionJson::fromJson(legacyChildJson,&fineOnly,&error)&&!fineOnly.hasCoarseExperiment&&fineOnly.hasFineExperiment&&fineOnly.fineExperiment.parentArtifactIdentity==artifact.artifactIdentity,"legacy v2 fine child remains loadable");
    FitCalibrationExperiment emptyExperiment;ok&=require(FitCalibrationEvidencePolicy::guidanceText(emptyExperiment).contains("Load"),"guidance prompts when no experiment is loaded");ok&=require(FitCalibrationEvidencePolicy::guidanceText(artifact.ok?RoundTechnicCalibrationArtifact::observationTemplate(artifact):FitCalibrationExperiment()).contains("coarse"),"guidance prompts for coarse observations");ok&=require(FitCalibrationEvidencePolicy::guidanceText(experiment).contains("Generate Fine Search"),"guidance advances selected coarse evidence");ok&=require(FitCalibrationEvidencePolicy::guidanceText(child).contains("fine-search"),"guidance prompts for new fine evidence");ok&=require(FitCalibrationEvidencePolicy::guidanceText(verification).contains("stale"),"guidance identifies stale evidence");
    QJsonObject legacyV1{{"formatVersion",1},{"artifactIdentity","legacy-coarse-v1"},{"featureFamily","RoundTechnicPassage"},{"featureRole","female"},{"orientationIdentity","legacy-modeled-orientation"},{"printerIdentity","Legacy Printer"},{"materialIdentity","Legacy PETG"},{"candidates",QJsonArray{QJsonObject{{"index",1},{"diameterCorrectionMillimetres",0.1},{"functionalDiameterMillimetres",4.9},{"observation","acceptable"},{"repeatNumber",1}}}}};FitCalibrationSession legacyV1Session;ok&=require(FitCalibrationSessionJson::fromJson(legacyV1,&legacyV1Session,&error)&&legacyV1Session.hasCoarseExperiment&&legacyV1Session.coarseExperiment.candidates.front().observations.size()==1&&legacyV1Session.process.printerIdentity=="Legacy Printer","legacy v1 experiment upgrades without observation loss");
    auto readyGuidance=verification;readyGuidance.state=FitEvidenceState::CandidateSelected;ok&=require(FitCalibrationEvidencePolicy::guidanceText(readyGuidance).contains("Click Mark Verified"),"complete evidence guidance requests explicit verification");ok&=require(FitCalibrationEvidencePolicy::markVerified(&readyGuidance,&error)&&FitCalibrationEvidencePolicy::guidanceText(readyGuidance).contains("Click Save"),"verified guidance requests persistence");
    return ok?0:1;
}
