#include "../src/services/geometry/print/PrintMeshAnalysis.h"
#include <QCoreApplication>
#include <QTextStream>
#include <cmath>
#include <limits>
using namespace PrintGeometry;
namespace { bool check(bool v,const char*m){if(!v)QTextStream(stderr)<<"FAIL: "<<m<<Qt::endl;return v;}
PrintMesh box(double x0=0,double y0=0,double z0=0,double x1=1,double y1=1,double z1=1){PrintMesh m;m.vertices={{x0,y0,z0},{x1,y0,z0},{x1,y1,z0},{x0,y1,z0},{x0,y0,z1},{x1,y0,z1},{x1,y1,z1},{x0,y1,z1}};m.faces={{0,2,1},{0,3,2},{4,5,6},{4,6,7},{0,1,5},{0,5,4},{3,7,6},{3,6,2},{0,4,7},{0,7,3},{1,2,6},{1,6,5}};return m;}
PrintMesh append(PrintMesh a,const PrintMesh&b){auto n=std::uint32_t(a.vertices.size());a.vertices.insert(a.vertices.end(),b.vertices.begin(),b.vertices.end());for(auto f:b.faces){for(auto&i:f)i+=n;a.faces.push_back(f);}return a;}
bool equivalent(const PrintMesh&mesh,std::size_t limit=20000000){MeshAnalysisOptions options;options.maximumCandidatePairs=limit;const auto indexed=analyzeSource(mesh,options);options.referenceBroadPhase=true;const auto reference=analyzeSource(mesh,options);bool same=indexed.vertices==reference.vertices&&indexed.triangles==reference.triangles&&indexed.invalidVertices==reference.invalidVertices&&indexed.invalidIndices==reference.invalidIndices&&indexed.degenerateFaces==reference.degenerateFaces&&indexed.duplicateFaces==reference.duplicateFaces&&indexed.boundaryEdges==reference.boundaryEdges&&indexed.nonManifoldEdges==reference.nonManifoldEdges&&indexed.nonManifoldVertices==reference.nonManifoldVertices&&indexed.selfIntersections==reference.selfIntersections&&indexed.connectedComponents==reference.connectedComponents&&indexed.broadPhaseCandidatePairs==reference.broadPhaseCandidatePairs&&indexed.narrowPhaseChecks==reference.narrowPhaseChecks&&indexed.finite==reference.finite&&indexed.indicesValid==reference.indicesValid&&indexed.consistentlyOriented==reference.consistentlyOriented&&indexed.resourceLimitExceeded==reference.resourceLimitExceeded&&indexed.signedVolume==reference.signedVolume&&validateBooleanOperand(indexed).error==validateBooleanOperand(reference).error&&indexed.issues.size()==reference.issues.size();if(same)for(std::size_t i=0;i<indexed.issues.size();++i){const auto&a=indexed.issues[i],&b=reference.issues[i];if(a.type!=b.type||a.first!=b.first||a.second!=b.second){same=false;break;}}return same;}}
int main(int argc,char**argv){QCoreApplication app(argc,argv);bool ok=true;auto cube=box();auto a=analyzeSource(cube);ok&=check(validateBooleanOperand(a).ok(),"closed cube operand");ok&=check(a.connectedComponents==1&&a.boundaryEdges==0,"closed cube topology");auto open=cube;open.faces.pop_back();auto oa=analyzeSource(open);ok&=check(oa.boundaryEdges>0&&validateBooleanOperand(oa).error==MeshValidationError::BoundaryEdge,"open source descriptive but invalid operand");auto bad=cube;bad.vertices[0].x=std::numeric_limits<double>::quiet_NaN();ok&=check(!analyzeSource(bad).finite,"non-finite vertex");bad=cube;bad.faces[0][0]=999;ok&=check(!analyzeSource(bad).indicesValid,"invalid index");bad=cube;bad.faces.push_back({0,0,1});ok&=check(analyzeSource(bad).degenerateFaces==1,"degenerate face");bad=cube;bad.faces.push_back(bad.faces.front());ok&=check(analyzeSource(bad).duplicateFaces==1,"duplicate face");auto separated=append(cube,box(10,10,10,11,11,11));auto sa=analyzeSource(separated);ok&=check(sa.connectedComponents==2,"multiple components");ok&=check(sa.broadPhaseCandidatePairs<sa.triangles*(sa.triangles-1)/2,"broad phase prunes separated faces");auto repeated=analyzeSource(separated);ok&=check(sa.broadPhaseCandidatePairs==repeated.broadPhaseCandidatePairs&&sa.selfIntersections==repeated.selfIntersections,"deterministic analysis");MeshAnalysisOptions bounded;bounded.maximumCandidatePairs=0;auto limited=analyzeSource(append(cube,cube),bounded);ok&=check(limited.resourceLimitExceeded&&validateBooleanOperand(limited).error==MeshValidationError::ResourceLimitExceeded,"candidate budget has typed failure");ok&=check(!a.issues.size(),"valid mesh has no issues");ok&=check(equivalent(cube)&&equivalent(open)&&equivalent(separated)&&equivalent(append(cube,box(.5,.5,.5,1.5,1.5,1.5)))&&equivalent(append(cube,cube),0),"indexed and reference strict analysis agree on valid, open, disconnected, intersecting, and bounded meshes");return ok?0:1;}
