#include "FrictionlessTechnicPinSemantic.h"
#include "../LDrawSourceModel.h"
#include <QCryptographicHash>
#include <QVector3D>
#include <cmath>
namespace PrintGeometry { namespace {
Point convert(const QVector3D&p){return {.4*double(p.x()),.4*double(p.z()),-.4*double(p.y())};}
Point direction(const std::array<double,12>&t,double x,double y,double z){QVector3D p(float(t[0]*x+t[1]*y+t[2]*z),float(t[4]*x+t[5]*y+t[6]*z),float(t[8]*x+t[9]*y+t[10]*z));auto q=convert(p);const double l=std::sqrt(q.x*q.x+q.y*q.y+q.z*q.z);return {q.x/l,q.y/l,q.z/l};}
Point cross(const Point&a,const Point&b){return {a.y*b.z-a.z*b.y,a.z*b.x-a.x*b.z,a.x*b.y-a.y*b.x};}
}
FunctionalFeature FrictionlessTechnicPinSemantic::canonicalPrototype(){FunctionalFeature f;f.stableIdentity="official-connect-frictionless-pin-prototype";f.family=FunctionalInterfaceFamily::FrictionlessTechnicPin;f.role=FunctionalInterfaceRole::Male;f.materialSide=FunctionalMaterialSide::MaterialInside;f.eligibility=FunctionalEligibility::Eligible;f.confidence=SemanticConfidence::HighConfidence;f.frame={{0,0,0},{0,0,1},{1,0,0},{0,1,0},false};f.nominalRadiusMillimetres=3.2;f.nominalDiameterMillimetres=6.4;f.nominalAxialExtentMillimetres=7.2;f.nominalEngagementExtentMillimetres=6.4;f.protectedInnerRadiusMillimetres=1.6;f.operandAction=FunctionalOperandAction::Unite;f.constructionRecipe="frictionless-technic-pin-connect-v1";f.evidenceContract="official-ldraw-connect-frictionless-pin-v1";f.radialProfile={{0,3.2},{.8,3.2},{3.4,2.4},{6.4,2.4},{7.2,2.52}};f.governingOperandIdentity=f.stableIdentity+":operand";return f;}
QVector<FunctionalFeature> FrictionlessTechnicPinSemantic::recognize(const LDrawGeometry::LDrawLoadResult&source){QVector<FunctionalFeature>out;if(!source.sourceModel)return out;for(const auto&r:source.sourceModel->references){if(r.fileId<0||r.fileId>=source.sourceModel->files.size())continue;const QString path=source.sourceModel->files[r.fileId].relativePath;if(path.compare("p/connect.dat",Qt::CaseInsensitive)!=0&&path.compare("connect.dat",Qt::CaseInsensitive)!=0)continue;auto f=canonicalPrototype();const auto&t=r.accumulatedTransform;f.frame.origin=convert(QVector3D(float(t[3]-2*t[1]),float(t[7]-2*t[5]),float(t[11]-2*t[9])));f.frame.axis=direction(t,0,-1,0);f.frame.profileU=direction(t,1,0,0);f.frame.profileV=cross(f.frame.axis,f.frame.profileU);f.frame.mirrored=r.mirrored;QCryptographicHash h(QCryptographicHash::Sha256);h.addData(QString("%1|%2|%3|%4").arg(r.id).arg(r.sourceLine).arg(f.frame.origin.x,0,'g',17).arg(f.frame.origin.y,0,'g',17).toUtf8());f.stableIdentity="frictionless-technic-pin:"+QString::fromLatin1(h.result().toHex());f.governingOperandIdentity=f.stableIdentity+":operand";f.provenance.push_back({path,r.id,r.sourceLine,r.inverted});out.push_back(f);}return out;}
}
