#include "FrictionTechnicPinSemantic.h"
#include <QCryptographicHash>
#include <QVector3D>
#include <cmath>
namespace PrintGeometry { namespace {
Point convert(const QVector3D&p){return {double(p.x())*.4,double(-p.z())*.4,double(-p.y())*.4};}
Point direction(const std::array<double,12>&t,double x,double y,double z){QVector3D p(float(t[0]*x+t[1]*y+t[2]*z),float(t[4]*x+t[5]*y+t[6]*z),float(t[8]*x+t[9]*y+t[10]*z));p=QVector3D(p.x(),-p.z(),-p.y());if(!qFuzzyIsNull(p.length()))p.normalize();return {p.x(),p.y(),p.z()};}
Point cross(const Point&a,const Point&b){return {a.y*b.z-a.z*b.y,a.z*b.x-a.x*b.z,a.x*b.y-a.y*b.x};}
}
FunctionalFeature FrictionTechnicPinSemantic::canonicalPrototype(){FunctionalFeature f;f.stableIdentity="official-confric5-friction-pin-prototype";f.family=FunctionalInterfaceFamily::FrictionTechnicPin;f.role=FunctionalInterfaceRole::Male;f.materialSide=FunctionalMaterialSide::MaterialInside;f.eligibility=FunctionalEligibility::Eligible;f.confidence=SemanticConfidence::HighConfidence;f.frame={{0,0,0},{0,0,1},{1,0,0},{0,1,0},false};f.nominalRadiusMillimetres=2.5;f.nominalDiameterMillimetres=5.0;f.nominalAxialExtentMillimetres=8.0;f.nominalEngagementExtentMillimetres=6.4;f.protectedInnerRadiusMillimetres=1.6;f.operandAction=FunctionalOperandAction::Unite;f.constructionRecipe="friction-technic-pin-confric5-ridge-v1";f.evidenceContract="official-ldraw-confric5-friction-pin-v1";f.radialProfile={{0,2.4},{.8,2.4},{1.2,2.5},{6.4,2.5},{7.2,2.4},{8.0,2.4}};f.governingOperandIdentity=f.stableIdentity+":operand";return f;}
QVector<FunctionalFeature> FrictionTechnicPinSemantic::recognize(const LDrawGeometry::LDrawLoadResult&source){QVector<FunctionalFeature>out;if(!source.sourceModel)return out;for(const auto&r:source.sourceModel->references){if(r.fileId<0||r.fileId>=source.sourceModel->files.size())continue;const QString path=source.sourceModel->files[r.fileId].relativePath;if(path.compare("p/confric5.dat",Qt::CaseInsensitive)!=0&&path.compare("confric5.dat",Qt::CaseInsensitive)!=0)continue;auto f=canonicalPrototype();const auto&t=r.accumulatedTransform;f.frame.origin=convert(QVector3D(float(t[3]),float(t[7]),float(t[11])));f.frame.axis=direction(t,0,-1,0);f.frame.profileU=direction(t,1,0,0);f.frame.profileV=cross(f.frame.axis,f.frame.profileU);f.frame.mirrored=r.mirrored;QCryptographicHash h(QCryptographicHash::Sha256);h.addData(QString("%1|%2|%3|%4").arg(r.id).arg(r.sourceLine).arg(f.frame.origin.x,0,'g',17).arg(f.frame.origin.y,0,'g',17).toUtf8());f.stableIdentity="friction-technic-pin:"+QString::fromLatin1(h.result().toHex());f.governingOperandIdentity=f.stableIdentity+":operand";f.provenance.push_back({path,r.id,r.sourceLine,r.inverted});out.push_back(f);}return out;}
}
