#include "FunctionalOperandRegenerator.h"

#include "PrintMeshAnalysis.h"

#include <algorithm>
#include <array>
#include <cmath>

namespace PrintGeometry {
namespace {
constexpr int RoundProfileSegments = 16;
constexpr double ContractTolerance = 1e-6;
constexpr double MinimumRadiusMillimetres = 1e-4;

double dot(const Point&a,const Point&b){return a.x*b.x+a.y*b.y+a.z*b.z;}
double length(const Point&p){return std::sqrt(dot(p,p));}
Point cross(const Point&a,const Point&b){return {a.y*b.z-a.z*b.y,a.z*b.x-a.x*b.z,a.x*b.y-a.y*b.x};}
void normalize(PrintMesh*mesh){const auto analysis=analyzeSource(*mesh);if(analysis.signedVolume<0.0)for(auto&face:mesh->faces)std::swap(face[1],face[2]);}

FunctionalOperandRegenerationResult failure(FunctionalOperandRegenerationError error,const FunctionalFeature&feature,FemaleClearanceDiameterCorrection correction,const QString&diagnostic)
{
    FunctionalOperandRegenerationResult result;result.error=error;result.featureIdentity=feature.stableIdentity;result.requestedDiameterCorrectionMillimetres=correction.millimetres;result.diagnostic=diagnostic;return result;
}
}

FunctionalOperandRegenerationResult FunctionalOperandRegenerator::regenerate(const FunctionalFeature&feature,FemaleClearanceDiameterCorrection correction)
{
    if(feature.family!=FunctionalInterfaceFamily::RoundTechnicPassage||feature.role!=FunctionalInterfaceRole::Female||feature.materialSide!=FunctionalMaterialSide::EmptyInsideMaterialOutside||feature.operandAction!=FunctionalOperandAction::Subtract||feature.eligibility!=FunctionalEligibility::Eligible||feature.confidence!=SemanticConfidence::HighConfidence||feature.constructionRecipe!=QStringLiteral("round-through-passage-v1"))
        return failure(FunctionalOperandRegenerationError::UnsupportedFeature,feature,correction,QStringLiteral("The functional feature is not eligible for round female-passage regeneration."));
    if(feature.stableIdentity.isEmpty()||feature.radialProfile.size()<2||!std::isfinite(correction.millimetres)||!std::isfinite(feature.nominalRadiusMillimetres)||feature.nominalRadiusMillimetres<=MinimumRadiusMillimetres)
        return failure(FunctionalOperandRegenerationError::InvalidContract,feature,correction,QStringLiteral("The retained functional contract is incomplete or non-finite."));
    const auto&frame=feature.frame;const double axisLength=length(frame.axis),uLength=length(frame.profileU),vLength=length(frame.profileV);
    if(std::abs(axisLength-1.0)>ContractTolerance||std::abs(uLength-1.0)>ContractTolerance||std::abs(vLength-1.0)>ContractTolerance||std::abs(dot(frame.axis,frame.profileU))>ContractTolerance||std::abs(dot(frame.axis,frame.profileV))>ContractTolerance||std::abs(dot(frame.profileU,frame.profileV))>ContractTolerance||dot(cross(frame.axis,frame.profileU),frame.profileV)<1.0-ContractTolerance)
        return failure(FunctionalOperandRegenerationError::InvalidContract,feature,correction,QStringLiteral("The retained functional frame is not right-handed and orthonormal."));

    FunctionalOperandRegenerationResult result;result.featureIdentity=feature.stableIdentity;result.requestedDiameterCorrectionMillimetres=correction.millimetres;result.resultingGoverningRadiusMillimetres=feature.nominalRadiusMillimetres+correction.millimetres*.5;result.executedProfile=feature.radialProfile;
    if(result.resultingGoverningRadiusMillimetres<=MinimumRadiusMillimetres)
        return failure(FunctionalOperandRegenerationError::UnsafeCorrection,feature,correction,QStringLiteral("The correction would collapse or invert the governing clearance profile."));

    double smallestProtectedRadius=1e100;int governedSections=0;
    for(auto&section:result.executedProfile){if(!std::isfinite(section.axialPositionMillimetres)||!std::isfinite(section.radiusMillimetres)||section.radiusMillimetres<=MinimumRadiusMillimetres)return failure(FunctionalOperandRegenerationError::InvalidContract,feature,correction,QStringLiteral("The retained radial profile is invalid."));if(std::abs(section.radiusMillimetres-feature.nominalRadiusMillimetres)<=ContractTolerance){section.radiusMillimetres=result.resultingGoverningRadiusMillimetres;++governedSections;}else smallestProtectedRadius=std::min(smallestProtectedRadius,section.radiusMillimetres);}
    for(int i=1;i<result.executedProfile.size();++i)if(result.executedProfile[i].axialPositionMillimetres+ContractTolerance<result.executedProfile[i-1].axialPositionMillimetres)return failure(FunctionalOperandRegenerationError::InvalidContract,feature,correction,QStringLiteral("The retained radial profile is not axially ordered."));
    if(governedSections==0)return failure(FunctionalOperandRegenerationError::InvalidContract,feature,correction,QStringLiteral("The retained profile has no governed clearance sections."));
    if(smallestProtectedRadius<1e99&&result.resultingGoverningRadiusMillimetres>=smallestProtectedRadius-ContractTolerance)return failure(FunctionalOperandRegenerationError::UnsafeCorrection,feature,correction,QStringLiteral("The correction would collapse the protected entrance transition."));

    auto&mesh=result.mesh;const double pi=3.14159265358979323846;
    for(const auto&section:result.executedProfile)for(int i=0;i<RoundProfileSegments;++i){const double angle=2.0*pi*double(i)/double(RoundProfileSegments),cs=std::cos(angle),sn=std::sin(angle);const Point radial{frame.profileU.x*cs+frame.profileV.x*sn,frame.profileU.y*cs+frame.profileV.y*sn,frame.profileU.z*cs+frame.profileV.z*sn};mesh.vertices.push_back({frame.origin.x+frame.axis.x*section.axialPositionMillimetres+radial.x*section.radiusMillimetres,frame.origin.y+frame.axis.y*section.axialPositionMillimetres+radial.y*section.radiusMillimetres,frame.origin.z+frame.axis.z*section.axialPositionMillimetres+radial.z*section.radiusMillimetres});}
    for(int section=0;section+1<result.executedProfile.size();++section)for(int i=0;i<RoundProfileSegments;++i){const int next=(i+1)%RoundProfileSegments;const auto a=std::uint32_t(section*RoundProfileSegments+i),b=std::uint32_t(section*RoundProfileSegments+next),d=std::uint32_t((section+1)*RoundProfileSegments+i),e=std::uint32_t((section+1)*RoundProfileSegments+next);mesh.faces.push_back({a,b,d});mesh.faces.push_back({b,e,d});}
    const auto firstCenter=std::uint32_t(mesh.vertices.size());const auto&first=result.executedProfile.front();mesh.vertices.push_back({frame.origin.x+frame.axis.x*first.axialPositionMillimetres,frame.origin.y+frame.axis.y*first.axialPositionMillimetres,frame.origin.z+frame.axis.z*first.axialPositionMillimetres});const auto lastCenter=std::uint32_t(mesh.vertices.size());const auto&last=result.executedProfile.back();mesh.vertices.push_back({frame.origin.x+frame.axis.x*last.axialPositionMillimetres,frame.origin.y+frame.axis.y*last.axialPositionMillimetres,frame.origin.z+frame.axis.z*last.axialPositionMillimetres});const auto lastBase=std::uint32_t((result.executedProfile.size()-1)*RoundProfileSegments);
    for(int i=0;i<RoundProfileSegments;++i){const auto next=std::uint32_t((i+1)%RoundProfileSegments);mesh.faces.push_back({firstCenter,next,std::uint32_t(i)});mesh.faces.push_back({lastCenter,lastBase+std::uint32_t(i),lastBase+next});}
    normalize(&mesh);result.analysis=analyzeSource(mesh);const auto validation=validateBooleanOperand(result.analysis);if(!validation.ok())return failure(FunctionalOperandRegenerationError::InvalidGeneratedOperand,feature,correction,QStringLiteral("The regenerated operand failed validation: %1").arg(QString::fromStdString(validation.message)));
    result.error=FunctionalOperandRegenerationError::None;result.diagnostic=QStringLiteral("Functional operand regenerated from the retained semantic contract.");return result;
}

FunctionalOperandRegenerationResult FunctionalOperandRegenerator::regenerateStud(const FunctionalFeature&feature,MaleStudDimensionalCorrection correction)
{
    FunctionalOperandRegenerationResult result;result.featureIdentity=feature.stableIdentity;result.requestedDiameterCorrectionMillimetres=correction.diameterMillimetres;result.requestedHeightCorrectionMillimetres=correction.heightMillimetres;
    const bool solid=feature.constructionRecipe==QStringLiteral("standard-solid-stud-v1"),open=feature.constructionRecipe==QStringLiteral("standard-open-stud-v1");
    if(feature.family!=FunctionalInterfaceFamily::StandardStud||feature.role!=FunctionalInterfaceRole::Male||feature.materialSide!=FunctionalMaterialSide::MaterialInside||feature.operandAction!=FunctionalOperandAction::Unite||feature.eligibility!=FunctionalEligibility::Eligible||feature.confidence!=SemanticConfidence::HighConfidence||(!solid&&!open)){
        result.error=FunctionalOperandRegenerationError::UnsupportedFeature;result.diagnostic=QStringLiteral("The functional feature is not an eligible standard stud contract.");return result;}
    if(feature.stableIdentity.isEmpty()||!std::isfinite(correction.diameterMillimetres)||!std::isfinite(correction.heightMillimetres)||feature.nominalRadiusMillimetres<=MinimumRadiusMillimetres||feature.nominalAxialExtentMillimetres<=MinimumRadiusMillimetres){result.error=FunctionalOperandRegenerationError::InvalidContract;result.diagnostic=QStringLiteral("The retained standard stud contract is incomplete or non-finite.");return result;}
    const auto&frame=feature.frame;const double axisLength=length(frame.axis),uLength=length(frame.profileU),vLength=length(frame.profileV);if(std::abs(axisLength-1.0)>ContractTolerance||std::abs(uLength-1.0)>ContractTolerance||std::abs(vLength-1.0)>ContractTolerance||std::abs(dot(frame.axis,frame.profileU))>ContractTolerance||std::abs(dot(frame.axis,frame.profileV))>ContractTolerance||std::abs(dot(frame.profileU,frame.profileV))>ContractTolerance){result.error=FunctionalOperandRegenerationError::InvalidContract;result.diagnostic=QStringLiteral("The retained standard stud frame is not orthonormal.");return result;}
    result.resultingGoverningRadiusMillimetres=feature.nominalRadiusMillimetres+correction.diameterMillimetres*.5;result.resultingAxialExtentMillimetres=feature.nominalAxialExtentMillimetres+correction.heightMillimetres;if(result.resultingGoverningRadiusMillimetres<=MinimumRadiusMillimetres||result.resultingAxialExtentMillimetres<=MinimumRadiusMillimetres||(open&&(feature.protectedInnerRadiusMillimetres<=MinimumRadiusMillimetres||feature.protectedInnerRadiusMillimetres>=result.resultingGoverningRadiusMillimetres-ContractTolerance))){result.error=FunctionalOperandRegenerationError::UnsafeCorrection;result.diagnostic=QStringLiteral("The correction would collapse or invert the standard stud.");return result;}
    constexpr double intrusion=.05;result.executedProfile={{-intrusion,result.resultingGoverningRadiusMillimetres},{result.resultingAxialExtentMillimetres,result.resultingGoverningRadiusMillimetres}};auto&mesh=result.mesh;const double pi=3.14159265358979323846;
    for(const auto&section:result.executedProfile)for(int i=0;i<RoundProfileSegments;++i){const double angle=2.0*pi*double(i)/double(RoundProfileSegments),cs=std::cos(angle),sn=std::sin(angle);const Point radial{frame.profileU.x*cs+frame.profileV.x*sn,frame.profileU.y*cs+frame.profileV.y*sn,frame.profileU.z*cs+frame.profileV.z*sn};mesh.vertices.push_back({frame.origin.x+frame.axis.x*section.axialPositionMillimetres+radial.x*section.radiusMillimetres,frame.origin.y+frame.axis.y*section.axialPositionMillimetres+radial.y*section.radiusMillimetres,frame.origin.z+frame.axis.z*section.axialPositionMillimetres+radial.z*section.radiusMillimetres});}
    for(int i=0;i<RoundProfileSegments;++i){const int next=(i+1)%RoundProfileSegments;mesh.faces.push_back({std::uint32_t(i),std::uint32_t(next),std::uint32_t(RoundProfileSegments+i)});mesh.faces.push_back({std::uint32_t(next),std::uint32_t(RoundProfileSegments+next),std::uint32_t(RoundProfileSegments+i)});}if(solid){const auto bottom=std::uint32_t(mesh.vertices.size());mesh.vertices.push_back({frame.origin.x-frame.axis.x*intrusion,frame.origin.y-frame.axis.y*intrusion,frame.origin.z-frame.axis.z*intrusion});const auto top=std::uint32_t(mesh.vertices.size());mesh.vertices.push_back({frame.origin.x+frame.axis.x*result.resultingAxialExtentMillimetres,frame.origin.y+frame.axis.y*result.resultingAxialExtentMillimetres,frame.origin.z+frame.axis.z*result.resultingAxialExtentMillimetres});for(int i=0;i<RoundProfileSegments;++i){const auto next=std::uint32_t((i+1)%RoundProfileSegments);mesh.faces.push_back({bottom,next,std::uint32_t(i)});mesh.faces.push_back({top,std::uint32_t(RoundProfileSegments+i),std::uint32_t(RoundProfileSegments)+next});}}else{const auto innerBottom=std::uint32_t(mesh.vertices.size());for(double axial:{-intrusion,result.resultingAxialExtentMillimetres})for(int i=0;i<RoundProfileSegments;++i){const double angle=2.0*pi*double(i)/double(RoundProfileSegments),cs=std::cos(angle),sn=std::sin(angle);const Point radial{frame.profileU.x*cs+frame.profileV.x*sn,frame.profileU.y*cs+frame.profileV.y*sn,frame.profileU.z*cs+frame.profileV.z*sn};mesh.vertices.push_back({frame.origin.x+frame.axis.x*axial+radial.x*feature.protectedInnerRadiusMillimetres,frame.origin.y+frame.axis.y*axial+radial.y*feature.protectedInnerRadiusMillimetres,frame.origin.z+frame.axis.z*axial+radial.z*feature.protectedInnerRadiusMillimetres});}const auto innerTop=innerBottom+RoundProfileSegments;for(int i=0;i<RoundProfileSegments;++i){const auto next=std::uint32_t((i+1)%RoundProfileSegments),outerBottom=std::uint32_t(i),outerTop=std::uint32_t(RoundProfileSegments+i),outerBottomNext=next,outerTopNext=std::uint32_t(RoundProfileSegments)+next,ib=innerBottom+std::uint32_t(i),ibn=innerBottom+next,it=innerTop+std::uint32_t(i),itn=innerTop+next;mesh.faces.push_back({ib,it,ibn});mesh.faces.push_back({ibn,it,itn});mesh.faces.push_back({outerBottom,ib,ibn});mesh.faces.push_back({outerBottom,ibn,outerBottomNext});mesh.faces.push_back({outerTop,itn,it});mesh.faces.push_back({outerTop,outerTopNext,itn});}}
    normalize(&mesh);result.analysis=analyzeSource(mesh);const auto validation=validateBooleanOperand(result.analysis);if(!validation.ok()){result.error=FunctionalOperandRegenerationError::InvalidGeneratedOperand;result.diagnostic=QStringLiteral("The regenerated standard stud failed validation: %1").arg(QString::fromStdString(validation.message));return result;}result.error=FunctionalOperandRegenerationError::None;result.diagnostic=open?QStringLiteral("Standard open stud regenerated with independent radial and axial corrections while preserving its bore."):QStringLiteral("Standard stud regenerated with independent radial and axial corrections.");return result;
}

FunctionalOperandRegenerationResult FunctionalOperandRegenerator::regenerateReceivingTube(
    const FunctionalFeature& feature, ReceivingTubeOutsideDiameterCorrection correction)
{
    FunctionalOperandRegenerationResult rejected;rejected.featureIdentity=feature.stableIdentity;rejected.requestedDiameterCorrectionMillimetres=correction.millimetres;
    if(feature.family!=FunctionalInterfaceFamily::StudReceivingClutch||feature.role!=FunctionalInterfaceRole::Female||feature.materialSide!=FunctionalMaterialSide::MaterialInside||feature.operandAction!=FunctionalOperandAction::Unite||feature.eligibility!=FunctionalEligibility::Eligible||feature.confidence!=SemanticConfidence::HighConfidence||feature.constructionRecipe!=QStringLiteral("stud-receiving-tube-wall-cell-v1")||feature.evidenceContract!=QStringLiteral("official-ldraw-stud4-tube-wall-cell-v1")){
        rejected.error=FunctionalOperandRegenerationError::UnsupportedFeature;rejected.diagnostic=QStringLiteral("The feature is not an eligible TubeWallCell receiving-tube contract.");return rejected;}
    FunctionalFeature annulus=feature;annulus.family=FunctionalInterfaceFamily::StandardStud;annulus.role=FunctionalInterfaceRole::Male;annulus.constructionRecipe=QStringLiteral("standard-open-stud-v1");
    auto result=regenerateStud(annulus,{correction.millimetres,0.0});result.featureIdentity=feature.stableIdentity;
    if(result.ok())result.diagnostic=QStringLiteral("TubeWallCell receiving-tube OD regenerated while preserving the protected bore and axial extent.");
    return result;
}

FunctionalOperandRegenerationResult FunctionalOperandRegenerator::regenerateReceivingPost(
    const FunctionalFeature& feature, ReceivingPostOutsideDiameterCorrection correction)
{
    FunctionalOperandRegenerationResult rejected;
    rejected.featureIdentity = feature.stableIdentity;
    rejected.requestedDiameterCorrectionMillimetres = correction.millimetres;
    if (feature.family != FunctionalInterfaceFamily::StudReceivingClutch
        || feature.role != FunctionalInterfaceRole::Female
        || feature.materialSide != FunctionalMaterialSide::MaterialInside
        || feature.operandAction != FunctionalOperandAction::Unite
        || feature.eligibility != FunctionalEligibility::Eligible
        || feature.confidence != SemanticConfidence::HighConfidence
        || feature.constructionRecipe != QStringLiteral("stud-receiving-post-wall-cell-v1")
        || feature.evidenceContract != QStringLiteral("official-ldraw-stud3-post-wall-cell-v1")) {
        rejected.error = FunctionalOperandRegenerationError::UnsupportedFeature;
        rejected.diagnostic = QStringLiteral("The feature is not an eligible PostWallCell receiving-post contract.");
        return rejected;
    }
    FunctionalFeature post = feature;
    post.family = FunctionalInterfaceFamily::StandardStud;
    post.role = FunctionalInterfaceRole::Male;
    post.constructionRecipe = QStringLiteral("standard-solid-stud-v1");
    auto result = regenerateStud(post, {correction.millimetres, 0.0});
    result.featureIdentity = feature.stableIdentity;
    if (result.ok()) result.diagnostic = QStringLiteral("PostWallCell post OD regenerated while preserving post height, wall positions, seating depth, and cell pitch.");
    return result;
}

FunctionalOperandRegenerationResult FunctionalOperandRegenerator::regenerateFrictionlessPin(
    const FunctionalFeature&feature,FrictionlessPinEnvelopeDiameterCorrection correction)
{
    FunctionalOperandRegenerationResult r;r.featureIdentity=feature.stableIdentity;r.requestedDiameterCorrectionMillimetres=correction.millimetres;
    if(feature.family!=FunctionalInterfaceFamily::FrictionlessTechnicPin||feature.role!=FunctionalInterfaceRole::Male||feature.materialSide!=FunctionalMaterialSide::MaterialInside||feature.operandAction!=FunctionalOperandAction::Unite||feature.eligibility!=FunctionalEligibility::Eligible||feature.confidence!=SemanticConfidence::HighConfidence||feature.constructionRecipe!=QStringLiteral("frictionless-technic-pin-connect-v1")||feature.evidenceContract!=QStringLiteral("official-ldraw-connect-frictionless-pin-v1")){r.error=FunctionalOperandRegenerationError::UnsupportedFeature;r.diagnostic="The feature is not an eligible frictionless Technic-pin contract.";return r;}
    if(feature.radialProfile.size()<2||feature.protectedInnerRadiusMillimetres<=0||!std::isfinite(correction.millimetres)){r.error=FunctionalOperandRegenerationError::InvalidContract;r.diagnostic="The retained frictionless-pin contract is incomplete.";return r;}
    r.resultingGoverningRadiusMillimetres=feature.nominalRadiusMillimetres+correction.millimetres*.5;r.resultingAxialExtentMillimetres=feature.nominalAxialExtentMillimetres;r.executedProfile=feature.radialProfile;
    if(r.resultingGoverningRadiusMillimetres<=feature.protectedInnerRadiusMillimetres+ContractTolerance){r.error=FunctionalOperandRegenerationError::UnsafeCorrection;r.diagnostic="The correction would collapse the protected pin bore.";return r;}
    const double radialDelta=correction.millimetres*.5;for(auto&section:r.executedProfile)section.radiusMillimetres+=radialDelta;
    constexpr int Segments=28;constexpr double GapHalfAngle=.14;const int points=Segments+1;auto point=[&](double axial,double radius,double angle){const double cs=std::cos(angle),sn=std::sin(angle);const auto&f=feature.frame;return Point{f.origin.x+f.axis.x*axial+(f.profileU.x*cs+f.profileV.x*sn)*radius,f.origin.y+f.axis.y*axial+(f.profileU.y*cs+f.profileV.y*sn)*radius,f.origin.z+f.axis.z*axial+(f.profileU.z*cs+f.profileV.z*sn)*radius};};
    auto&m=r.mesh;for(const auto&s:r.executedProfile)for(int i=0;i<points;++i){const double a=GapHalfAngle+(2*3.14159265358979323846-2*GapHalfAngle)*double(i)/Segments;m.vertices.push_back(point(s.axialPositionMillimetres,s.radiusMillimetres,a));}const auto innerBase=std::uint32_t(m.vertices.size());for(const auto&s:r.executedProfile)for(int i=0;i<points;++i){const double a=GapHalfAngle+(2*3.14159265358979323846-2*GapHalfAngle)*double(i)/Segments;m.vertices.push_back(point(s.axialPositionMillimetres,feature.protectedInnerRadiusMillimetres,a));}
    const int sections=r.executedProfile.size();for(int s=0;s+1<sections;++s)for(int i=0;i<Segments;++i){const auto a=std::uint32_t(s*points+i),b=a+1,c=std::uint32_t((s+1)*points+i),d=c+1;m.faces.push_back({a,b,c});m.faces.push_back({b,d,c});const auto ia=innerBase+a,ib=innerBase+b,ic=innerBase+c,id=innerBase+d;m.faces.push_back({ia,ic,ib});m.faces.push_back({ib,ic,id});}
    for(int s=0;s+1<sections;++s)for(int edge:{0,Segments}){const auto o0=std::uint32_t(s*points+edge),o1=std::uint32_t((s+1)*points+edge),i0=innerBase+o0,i1=innerBase+o1;if(edge==0){m.faces.push_back({o0,o1,i0});m.faces.push_back({i0,o1,i1});}else{m.faces.push_back({o0,i0,o1});m.faces.push_back({i0,i1,o1});}}
    for(int end:{0,sections-1})for(int i=0;i<Segments;++i){const auto o=std::uint32_t(end*points+i),on=o+1,ii=innerBase+o,in=innerBase+on;if(end==0){m.faces.push_back({o,ii,on});m.faces.push_back({on,ii,in});}else{m.faces.push_back({o,on,ii});m.faces.push_back({on,in,ii});}}
    normalize(&m);r.analysis=analyzeSource(m);const auto valid=validateBooleanOperand(r.analysis);if(!valid.ok()){r.error=FunctionalOperandRegenerationError::InvalidGeneratedOperand;r.diagnostic=QString("The regenerated frictionless pin failed validation: %1").arg(QString::fromStdString(valid.message));return r;}r.error=FunctionalOperandRegenerationError::None;r.diagnostic="Frictionless Technic-pin envelope regenerated while preserving its bore, slot, engagement length, and axial profile.";return r;
}

FunctionalOperandRegenerationResult FunctionalOperandRegenerator::regenerateFrictionPin(
    const FunctionalFeature&feature,FrictionPinRidgeEnvelopeDiameterCorrection correction)
{
    FunctionalOperandRegenerationResult r;r.featureIdentity=feature.stableIdentity;r.requestedDiameterCorrectionMillimetres=correction.millimetres;
    if(feature.family!=FunctionalInterfaceFamily::FrictionTechnicPin||feature.role!=FunctionalInterfaceRole::Male||feature.materialSide!=FunctionalMaterialSide::MaterialInside||feature.operandAction!=FunctionalOperandAction::Unite||feature.eligibility!=FunctionalEligibility::Eligible||feature.confidence!=SemanticConfidence::HighConfidence||feature.constructionRecipe!=QStringLiteral("friction-technic-pin-confric5-ridge-v1")||feature.evidenceContract!=QStringLiteral("official-ldraw-confric5-friction-pin-v1")){r.error=FunctionalOperandRegenerationError::UnsupportedFeature;r.diagnostic="The feature is not an eligible confric5 friction Technic-pin contract.";return r;}
    if(feature.radialProfile.size()<4||feature.protectedInnerRadiusMillimetres<=0||!std::isfinite(correction.millimetres)){r.error=FunctionalOperandRegenerationError::InvalidContract;r.diagnostic="The retained friction-pin ridge contract is incomplete.";return r;}
    constexpr double CoreRadius=2.4;r.resultingGoverningRadiusMillimetres=feature.nominalRadiusMillimetres+correction.millimetres*.5;r.resultingAxialExtentMillimetres=feature.nominalAxialExtentMillimetres;r.executedProfile=feature.radialProfile;if(r.resultingGoverningRadiusMillimetres<CoreRadius-ContractTolerance){r.error=FunctionalOperandRegenerationError::UnsafeCorrection;r.diagnostic="The ridge correction would collapse the protected 4.80 mm core envelope.";return r;}for(auto&s:r.executedProfile)if(std::abs(s.radiusMillimetres-feature.nominalRadiusMillimetres)<=ContractTolerance)s.radiusMillimetres=r.resultingGoverningRadiusMillimetres;
    constexpr int Segments=60;constexpr double GapHalfAngle=.16;const int points=Segments+1;const double pi=3.14159265358979323846;auto point=[&](double axial,double ridgeRadius,double angle){const double lobe=std::pow(std::max(0.0,std::cos(4.0*(angle-pi*.25))),2.0),radius=CoreRadius+(ridgeRadius-CoreRadius)*lobe,cs=std::cos(angle),sn=std::sin(angle);const auto&f=feature.frame;return Point{f.origin.x+f.axis.x*axial+(f.profileU.x*cs+f.profileV.x*sn)*radius,f.origin.y+f.axis.y*axial+(f.profileU.y*cs+f.profileV.y*sn)*radius,f.origin.z+f.axis.z*axial+(f.profileU.z*cs+f.profileV.z*sn)*radius};};auto innerPoint=[&](double axial,double angle){const double cs=std::cos(angle),sn=std::sin(angle);const auto&f=feature.frame;return Point{f.origin.x+f.axis.x*axial+(f.profileU.x*cs+f.profileV.x*sn)*feature.protectedInnerRadiusMillimetres,f.origin.y+f.axis.y*axial+(f.profileU.y*cs+f.profileV.y*sn)*feature.protectedInnerRadiusMillimetres,f.origin.z+f.axis.z*axial+(f.profileU.z*cs+f.profileV.z*sn)*feature.protectedInnerRadiusMillimetres};};
    auto&m=r.mesh;for(const auto&s:r.executedProfile)for(int i=0;i<points;++i){const double a=GapHalfAngle+(2*pi-2*GapHalfAngle)*double(i)/Segments;m.vertices.push_back(point(s.axialPositionMillimetres,s.radiusMillimetres,a));}const auto innerBase=std::uint32_t(m.vertices.size());for(const auto&s:r.executedProfile)for(int i=0;i<points;++i){const double a=GapHalfAngle+(2*pi-2*GapHalfAngle)*double(i)/Segments;m.vertices.push_back(innerPoint(s.axialPositionMillimetres,a));}const int sections=r.executedProfile.size();for(int s=0;s+1<sections;++s)for(int i=0;i<Segments;++i){const auto a=std::uint32_t(s*points+i),b=a+1,c=std::uint32_t((s+1)*points+i),d=c+1;m.faces.push_back({a,b,c});m.faces.push_back({b,d,c});const auto ia=innerBase+a,ib=innerBase+b,ic=innerBase+c,id=innerBase+d;m.faces.push_back({ia,ic,ib});m.faces.push_back({ib,ic,id});}for(int s=0;s+1<sections;++s)for(int edge:{0,Segments}){const auto o0=std::uint32_t(s*points+edge),o1=std::uint32_t((s+1)*points+edge),i0=innerBase+o0,i1=innerBase+o1;if(edge==0){m.faces.push_back({o0,o1,i0});m.faces.push_back({i0,o1,i1});}else{m.faces.push_back({o0,i0,o1});m.faces.push_back({i0,i1,o1});}}for(int end:{0,sections-1})for(int i=0;i<Segments;++i){const auto o=std::uint32_t(end*points+i),on=o+1,ii=innerBase+o,in=innerBase+on;if(end==0){m.faces.push_back({o,ii,on});m.faces.push_back({on,ii,in});}else{m.faces.push_back({o,on,ii});m.faces.push_back({on,in,ii});}}
    normalize(&m);r.analysis=analyzeSource(m);const auto valid=validateBooleanOperand(r.analysis);if(!valid.ok()){r.error=FunctionalOperandRegenerationError::InvalidGeneratedOperand;r.diagnostic=QString("The regenerated friction-pin coupon failed validation: %1").arg(QString::fromStdString(valid.message));return r;}r.error=FunctionalOperandRegenerationError::None;r.diagnostic="Friction-ridge envelope regenerated while preserving the 4.80 mm core, bore, compliance slot, entry transitions, and engagement length.";return r;
}

FunctionalOperandRegenerationResult FunctionalOperandRegenerator::regenerateTechnicAxleProfile(
    const FunctionalFeature&feature,TechnicAxleTipToTipCorrection correction)
{
    FunctionalOperandRegenerationResult r;r.featureIdentity=feature.stableIdentity;r.requestedDiameterCorrectionMillimetres=correction.millimetres;
    const bool male=feature.family==FunctionalInterfaceFamily::TechnicAxle&&feature.role==FunctionalInterfaceRole::Male&&feature.materialSide==FunctionalMaterialSide::MaterialInside&&feature.operandAction==FunctionalOperandAction::Unite&&feature.constructionRecipe==QStringLiteral("technic-axle-cross-profile-v1")&&feature.evidenceContract==QStringLiteral("official-ldraw-axle-cross-profile-v1");
    const bool female=feature.family==FunctionalInterfaceFamily::TechnicAxleHole&&feature.role==FunctionalInterfaceRole::Female&&feature.materialSide==FunctionalMaterialSide::EmptyInsideMaterialOutside&&feature.operandAction==FunctionalOperandAction::Subtract&&feature.constructionRecipe==QStringLiteral("technic-axle-hole-cross-profile-v1")&&feature.evidenceContract==QStringLiteral("official-ldraw-axlehole-cross-profile-v1");
    if((!male&&!female)||feature.eligibility!=FunctionalEligibility::Eligible||feature.confidence!=SemanticConfidence::HighConfidence){r.error=FunctionalOperandRegenerationError::UnsupportedFeature;r.diagnostic="The feature is not an eligible ordinary Technic axle cross-profile contract.";return r;}
    if(feature.stableIdentity.isEmpty()||!std::isfinite(correction.millimetres)||feature.nominalRadiusMillimetres<=0||feature.nominalAxialExtentMillimetres<=0||feature.protectedCrossArmHalfWidthMillimetres<=0||feature.nominalCrossShoulderRadiusMillimetres<=feature.protectedCrossArmHalfWidthMillimetres){r.error=FunctionalOperandRegenerationError::InvalidContract;r.diagnostic="The retained Technic axle cross-profile contract is incomplete.";return r;}
    const auto&f=feature.frame;const double axisLength=length(f.axis),uLength=length(f.profileU),vLength=length(f.profileV);if(std::abs(axisLength-1.0)>ContractTolerance||std::abs(uLength-1.0)>ContractTolerance||std::abs(vLength-1.0)>ContractTolerance||std::abs(dot(f.axis,f.profileU))>ContractTolerance||std::abs(dot(f.axis,f.profileV))>ContractTolerance||std::abs(dot(f.profileU,f.profileV))>ContractTolerance){r.error=FunctionalOperandRegenerationError::InvalidContract;r.diagnostic="The retained Technic axle frame is not orthonormal.";return r;}
    const double tip=feature.nominalRadiusMillimetres+correction.millimetres*.5,arm=feature.protectedCrossArmHalfWidthMillimetres,shoulder=feature.nominalCrossShoulderRadiusMillimetres+correction.millimetres*.5;if(tip<=shoulder||shoulder<=arm){r.error=FunctionalOperandRegenerationError::UnsafeCorrection;r.diagnostic="The correction would collapse or invert the protected Technic axle cross profile.";return r;}r.resultingGoverningRadiusMillimetres=tip;r.resultingAxialExtentMillimetres=feature.nominalAxialExtentMillimetres;r.executedProfile={{0,tip},{feature.nominalAxialExtentMillimetres,tip}};
    const std::array<std::array<double,2>,16>profile={{{tip,0},{shoulder,arm},{arm,arm},{arm,shoulder},{0,tip},{-arm,shoulder},{-arm,arm},{-shoulder,arm},{-tip,0},{-shoulder,-arm},{-arm,-arm},{-arm,-shoulder},{0,-tip},{arm,-shoulder},{arm,-arm},{shoulder,-arm}}};auto point=[&](double axial,const auto&p){return Point{f.origin.x+f.axis.x*axial+f.profileU.x*p[0]+f.profileV.x*p[1],f.origin.y+f.axis.y*axial+f.profileU.y*p[0]+f.profileV.y*p[1],f.origin.z+f.axis.z*axial+f.profileU.z*p[0]+f.profileV.z*p[1]};};auto&m=r.mesh;for(double axial:{0.0,feature.nominalAxialExtentMillimetres})for(const auto&p:profile)m.vertices.push_back(point(axial,p));for(int i=0;i<16;++i){const auto next=std::uint32_t((i+1)%16),a=std::uint32_t(i),b=next,c=std::uint32_t(16+i),d=std::uint32_t(16)+next;m.faces.push_back({a,b,c});m.faces.push_back({b,d,c});}const auto bottom=std::uint32_t(m.vertices.size());m.vertices.push_back(point(0.0,std::array<double,2>{0,0}));const auto top=std::uint32_t(m.vertices.size());m.vertices.push_back(point(feature.nominalAxialExtentMillimetres,std::array<double,2>{0,0}));for(int i=0;i<16;++i){const auto next=std::uint32_t((i+1)%16);m.faces.push_back({bottom,next,std::uint32_t(i)});m.faces.push_back({top,std::uint32_t(16+i),std::uint32_t(16)+next});}normalize(&m);r.analysis=analyzeSource(m);const auto valid=validateBooleanOperand(r.analysis);if(!valid.ok()){r.error=FunctionalOperandRegenerationError::InvalidGeneratedOperand;r.diagnostic=QString("The regenerated Technic axle profile failed validation: %1").arg(QString::fromStdString(valid.message));return r;}r.error=FunctionalOperandRegenerationError::None;r.diagnostic=QStringLiteral("Ordinary Technic axle cross profile regenerated by varying tip-to-tip envelope only; the %1 mm arm half-width, cross topology, and engagement length remain protected.").arg(arm,0,'f',3);return r;
}

FunctionalOperandRegenerationResult FunctionalOperandRegenerator::regenerateTechnicAxleHoleArmWidth(
    const FunctionalFeature&feature,TechnicAxleHoleArmWidthCorrection correction)
{
    FunctionalOperandRegenerationResult r;r.featureIdentity=feature.stableIdentity;r.requestedDiameterCorrectionMillimetres=correction.millimetres;
    const bool contract=feature.family==FunctionalInterfaceFamily::TechnicAxleHole&&feature.role==FunctionalInterfaceRole::Female&&feature.materialSide==FunctionalMaterialSide::EmptyInsideMaterialOutside&&feature.operandAction==FunctionalOperandAction::Subtract&&feature.constructionRecipe==QStringLiteral("technic-axle-hole-arm-width-clearance-v2")&&feature.evidenceContract==QStringLiteral("official-ldraw-axlehole-arm-width-clearance-v2");
    if(!contract||feature.eligibility!=FunctionalEligibility::Eligible||feature.confidence!=SemanticConfidence::HighConfidence){r.error=FunctionalOperandRegenerationError::UnsupportedFeature;r.diagnostic="The feature is not an eligible ordinary Technic axle-hole arm-width contract.";return r;}
    if(feature.stableIdentity.isEmpty()||!std::isfinite(correction.millimetres)||!std::isfinite(correction.fixedTipToTipCorrectionMillimetres)||feature.nominalRadiusMillimetres<=0||feature.nominalAxialExtentMillimetres<=0||feature.protectedCrossArmHalfWidthMillimetres<=0||feature.nominalCrossShoulderRadiusMillimetres<=feature.protectedCrossArmHalfWidthMillimetres){r.error=FunctionalOperandRegenerationError::InvalidContract;r.diagnostic="The retained Technic axle-hole arm-width contract is incomplete.";return r;}
    const auto&f=feature.frame;const double tip=feature.nominalRadiusMillimetres+correction.fixedTipToTipCorrectionMillimetres*.5,shoulder=feature.nominalCrossShoulderRadiusMillimetres+correction.fixedTipToTipCorrectionMillimetres*.5,arm=feature.protectedCrossArmHalfWidthMillimetres+correction.millimetres*.5;if(arm<=0||shoulder<=arm||tip<=shoulder){r.error=FunctionalOperandRegenerationError::UnsafeCorrection;r.diagnostic="The correction would collapse or invert the ordinary axle-hole cross profile.";return r;}r.resultingGoverningRadiusMillimetres=tip;r.resultingAxialExtentMillimetres=feature.nominalAxialExtentMillimetres;r.executedProfile={{0,tip},{feature.nominalAxialExtentMillimetres,tip}};
    const std::array<std::array<double,2>,16>profile={{{tip,0},{shoulder,arm},{arm,arm},{arm,shoulder},{0,tip},{-arm,shoulder},{-arm,arm},{-shoulder,arm},{-tip,0},{-shoulder,-arm},{-arm,-arm},{-arm,-shoulder},{0,-tip},{arm,-shoulder},{arm,-arm},{shoulder,-arm}}};auto point=[&](double axial,const auto&p){return Point{f.origin.x+f.axis.x*axial+f.profileU.x*p[0]+f.profileV.x*p[1],f.origin.y+f.axis.y*axial+f.profileU.y*p[0]+f.profileV.y*p[1],f.origin.z+f.axis.z*axial+f.profileU.z*p[0]+f.profileV.z*p[1]};};auto&m=r.mesh;for(double axial:{0.0,feature.nominalAxialExtentMillimetres})for(const auto&p:profile)m.vertices.push_back(point(axial,p));for(int i=0;i<16;++i){const auto next=std::uint32_t((i+1)%16),a=std::uint32_t(i),b=next,c=std::uint32_t(16+i),d=std::uint32_t(16)+next;m.faces.push_back({a,b,c});m.faces.push_back({b,d,c});}const auto bottom=std::uint32_t(m.vertices.size());m.vertices.push_back(point(0.0,std::array<double,2>{0,0}));const auto top=std::uint32_t(m.vertices.size());m.vertices.push_back(point(feature.nominalAxialExtentMillimetres,std::array<double,2>{0,0}));for(int i=0;i<16;++i){const auto next=std::uint32_t((i+1)%16);m.faces.push_back({bottom,next,std::uint32_t(i)});m.faces.push_back({top,std::uint32_t(16+i),std::uint32_t(16)+next});}normalize(&m);r.analysis=analyzeSource(m);const auto valid=validateBooleanOperand(r.analysis);if(!valid.ok()){r.error=FunctionalOperandRegenerationError::InvalidGeneratedOperand;r.diagnostic=QString("The regenerated Technic axle-hole arm-width profile failed validation: %1").arg(QString::fromStdString(valid.message));return r;}r.error=FunctionalOperandRegenerationError::None;r.diagnostic=QStringLiteral("Ordinary Technic axle-hole arm width regenerated to %1 mm while tip-to-tip remains fixed at %2 mm and engagement depth remains protected.").arg(arm*2,0,'f',3).arg(tip*2,0,'f',3);return r;
}

} // namespace PrintGeometry
