#include "PrintMeshAnalysis.h"
#include <algorithm>
#include <cmath>
#include <map>
#include <queue>
#include <set>
#include <tuple>

namespace PrintGeometry { namespace {
constexpr double E=1e-9;using Edge=std::pair<std::uint32_t,std::uint32_t>;
Edge edge(std::uint32_t a,std::uint32_t b){return a<b?Edge{a,b}:Edge{b,a};}
Point sub(const Point&a,const Point&b){return{a.x-b.x,a.y-b.y,a.z-b.z};}
Point cross(const Point&a,const Point&b){return{a.y*b.z-a.z*b.y,a.z*b.x-a.x*b.z,a.x*b.y-a.y*b.x};}
double dot(const Point&a,const Point&b){return a.x*b.x+a.y*b.y+a.z*b.z;}
double comp(const Point&p,int a){return a==0?p.x:a==1?p.y:p.z;}
double volume(const Point&a,const Point&b,const Point&c){return(a.x*(b.y*c.z-b.z*c.y)-a.y*(b.x*c.z-b.z*c.x)+a.z*(b.x*c.y-b.y*c.x))/6.0;}
double area2(const Point&a,const Point&b,const Point&c){auto n=cross(sub(b,a),sub(c,a));return dot(n,n);}
int sharedVertices(const Face&a,const Face&b){int n=0;for(auto x:a)for(auto y:b)if(x==y)++n;return n;}
struct P2{double x,y;};P2 project(const Point&p,int d){return d==0?P2{p.y,p.z}:d==1?P2{p.x,p.z}:P2{p.x,p.y};}
double orient(const P2&a,const P2&b,const P2&c){return(b.x-a.x)*(c.y-a.y)-(b.y-a.y)*(c.x-a.x);}
bool proper(const P2&a,const P2&b,const P2&c,const P2&d){double x=orient(a,b,c),y=orient(a,b,d),z=orient(c,d,a),w=orient(c,d,b);return((x>E&&y<-E)||(x<-E&&y>E))&&((z>E&&w<-E)||(z<-E&&w>E));}
bool inside(const P2&p,const P2&a,const P2&b,const P2&c){double x=orient(a,b,p),y=orient(b,c,p),z=orient(c,a,p);return(x>E&&y>E&&z>E)||(x<-E&&y<-E&&z<-E);}
bool coplanar(const Point&a,const Point&b,const Point&c,const Point&d,const Point&e,const Point&f,const Point&n){int drop=std::abs(n.x)>std::abs(n.y)&&std::abs(n.x)>std::abs(n.z)?0:std::abs(n.y)>std::abs(n.z)?1:2;P2 p[3]={project(a,drop),project(b,drop),project(c,drop)},q[3]={project(d,drop),project(e,drop),project(f,drop)};for(int i=0;i<3;++i)for(int j=0;j<3;++j)if(proper(p[i],p[(i+1)%3],q[j],q[(j+1)%3]))return true;P2 pc{(p[0].x+p[1].x+p[2].x)/3,(p[0].y+p[1].y+p[2].y)/3},qc{(q[0].x+q[1].x+q[2].x)/3,(q[0].y+q[1].y+q[2].y)/3};return inside(pc,q[0],q[1],q[2])||inside(qc,p[0],p[1],p[2]);}
bool segmentTriangle(const Point&p0,const Point&p1,const Point&a,const Point&b,const Point&c){auto direction=sub(p1,p0),e1=sub(b,a),e2=sub(c,a),h=cross(direction,e2);double determinant=dot(e1,h);if(std::abs(determinant)<E)return false;double inverse=1/determinant;auto s=sub(p0,a);double u=inverse*dot(s,h);if(u<=E||u>=1-E)return false;auto q=cross(s,e1);double v=inverse*dot(direction,q);if(v<=E||u+v>=1-E)return false;double t=inverse*dot(e2,q);return t>E&&t<1-E;}
struct Box{double lo[3],hi[3];};
Box faceBox(const PrintMesh&m,const Face&f){const auto&a=m.vertices[f[0]],&b=m.vertices[f[1]],&c=m.vertices[f[2]];return{{std::min({a.x,b.x,c.x}),std::min({a.y,b.y,c.y}),std::min({a.z,b.z,c.z})},{std::max({a.x,b.x,c.x}),std::max({a.y,b.y,c.y}),std::max({a.z,b.z,c.z})}};}
bool overlap(const Box&a,const Box&b){for(int i=0;i<3;++i)if(a.hi[i]+E<b.lo[i]||b.hi[i]+E<a.lo[i])return false;return true;}
bool intersects(const PrintMesh&m,const Face&l,const Face&r){const auto&a=m.vertices[l[0]],&b=m.vertices[l[1]],&c=m.vertices[l[2]],&d=m.vertices[r[0]],&e=m.vertices[r[1]],&f=m.vertices[r[2]];auto n1=cross(sub(b,a),sub(c,a)),n2=cross(sub(e,d),sub(f,d)),nc=cross(n1,n2);if(dot(nc,nc)<=E*E&&std::abs(dot(n1,sub(d,a)))<=E*std::sqrt(dot(n1,n1)))return coplanar(a,b,c,d,e,f,n1);return segmentTriangle(a,b,d,e,f)||segmentTriangle(b,c,d,e,f)||segmentTriangle(c,a,d,e,f)||segmentTriangle(d,e,a,b,c)||segmentTriangle(e,f,a,b,c)||segmentTriangle(f,d,a,b,c);}
MeshValidationResult invalid(MeshValidationError e,const char*m){return{e,m};}
}

MeshAnalysisResult analyzeSource(const PrintMesh&m,const MeshAnalysisOptions&o){MeshAnalysisResult r;r.vertices=m.vertices.size();r.triangles=m.faces.size();std::map<Edge,std::vector<int>>uses;std::map<Edge,std::vector<std::size_t>>faceUses;std::map<std::array<std::uint32_t,3>,std::size_t>faceSet;std::vector<std::vector<std::size_t>>adj(m.faces.size()),incident(m.vertices.size());
 for(std::size_t i=0;i<m.vertices.size();++i){const auto&p=m.vertices[i];if(!std::isfinite(p.x)||!std::isfinite(p.y)||!std::isfinite(p.z)){r.finite=false;++r.invalidVertices;if(o.collectIssues)r.issues.push_back({MeshIssueType::NonFiniteVertex,i,0});continue;}if(!r.bounds.valid){r.bounds.minimum=r.bounds.maximum=p;r.bounds.valid=true;}else for(int a=0;a<3;++a){double*lo=a==0?&r.bounds.minimum.x:a==1?&r.bounds.minimum.y:&r.bounds.minimum.z;double*hi=a==0?&r.bounds.maximum.x:a==1?&r.bounds.maximum.y:&r.bounds.maximum.z;*lo=std::min(*lo,comp(p,a));*hi=std::max(*hi,comp(p,a));}}
 for(std::size_t i=0;i<m.faces.size();++i){const auto&f=m.faces[i];if(f[0]>=m.vertices.size()||f[1]>=m.vertices.size()||f[2]>=m.vertices.size()){r.indicesValid=false;++r.invalidIndices;if(o.collectIssues)r.issues.push_back({MeshIssueType::InvalidIndex,i,0});continue;}auto canonical=f;std::sort(canonical.begin(),canonical.end());auto inserted=faceSet.emplace(canonical,i);if(!inserted.second){++r.duplicateFaces;if(o.collectIssues)r.issues.push_back({MeshIssueType::DuplicateFace,inserted.first->second,i});}if(f[0]==f[1]||f[1]==f[2]||f[2]==f[0]||area2(m.vertices[f[0]],m.vertices[f[1]],m.vertices[f[2]])<=1e-24){++r.degenerateFaces;if(o.collectIssues)r.issues.push_back({MeshIssueType::DegenerateFace,i,0});continue;}for(auto v:f)incident[v].push_back(i);r.signedVolume+=volume(m.vertices[f[0]],m.vertices[f[1]],m.vertices[f[2]]);for(auto d:{std::pair{f[0],f[1]},std::pair{f[1],f[2]},std::pair{f[2],f[0]}}){uses[edge(d.first,d.second)].push_back(d.first<d.second?1:-1);faceUses[edge(d.first,d.second)].push_back(i);}}
 for(const auto&e:uses){if(e.second.size()==1){++r.boundaryEdges;if(o.collectIssues)r.issues.push_back({MeshIssueType::BoundaryEdge,e.first.first,e.first.second});}else if(e.second.size()>2){++r.nonManifoldEdges;if(o.collectIssues)r.issues.push_back({MeshIssueType::NonManifoldEdge,e.first.first,e.first.second});}else if(e.second[0]==e.second[1])r.consistentlyOriented=false;}for(const auto&e:faceUses)if(e.second.size()==2){adj[e.second[0]].push_back(e.second[1]);adj[e.second[1]].push_back(e.second[0]);}
 std::vector<bool>seen(m.faces.size());for(std::size_t root=0;root<m.faces.size();++root)if(!seen[root]){++r.connectedComponents;std::queue<std::size_t>q;q.push(root);seen[root]=true;while(!q.empty()){auto at=q.front();q.pop();for(auto x:adj[at])if(!seen[x]){seen[x]=true;q.push(x);}}}
 for(std::uint32_t v=0;v<incident.size();++v){std::set<std::size_t>remaining(incident[v].begin(),incident[v].end());int fans=0;while(!remaining.empty()){++fans;std::queue<std::size_t>q;q.push(*remaining.begin());remaining.erase(remaining.begin());while(!q.empty()){auto fi=q.front();q.pop();const auto&f=m.faces[fi];for(int i=0;i<3;++i)if(f[i]==v){for(auto x:faceUses[edge(v,f[(i+1)%3])])if(remaining.erase(x))q.push(x);for(auto x:faceUses[edge(v,f[(i+2)%3])])if(remaining.erase(x))q.push(x);}}}if(fans>1){++r.nonManifoldVertices;if(o.collectIssues)r.issues.push_back({MeshIssueType::NonManifoldVertex,v,0});}}
 if(r.indicesValid){std::vector<Box>boxes;boxes.reserve(m.faces.size());for(const auto&f:m.faces)boxes.push_back(faceBox(m,f));std::vector<std::size_t>order(m.faces.size());for(std::size_t i=0;i<order.size();++i)order[i]=i;std::stable_sort(order.begin(),order.end(),[&](auto a,auto b){return boxes[a].lo[0]<boxes[b].lo[0];});for(std::size_t ai=0;ai<order.size();++ai){auto i=order[ai];for(std::size_t aj=ai+1;aj<order.size()&&boxes[order[aj]].lo[0]<=boxes[i].hi[0]+E;++aj){auto j=order[aj];if(!overlap(boxes[i],boxes[j])||sharedVertices(m.faces[i],m.faces[j])>=2)continue;if(++r.broadPhaseCandidatePairs>o.maximumCandidatePairs){r.resourceLimitExceeded=true;r.absoluteVolume=std::abs(r.signedVolume);return r;}++r.narrowPhaseChecks;if(intersects(m,m.faces[i],m.faces[j])){++r.selfIntersections;if(o.collectIssues)r.issues.push_back({MeshIssueType::SelfIntersection,i,j});}}}}
 r.absoluteVolume=std::abs(r.signedVolume);return r;}

MeshValidationResult validateBooleanOperand(const MeshAnalysisResult&a){if(a.resourceLimitExceeded)return invalid(MeshValidationError::ResourceLimitExceeded,"mesh analysis resource limit exceeded");if(a.triangles==0)return invalid(MeshValidationError::Empty,"mesh is empty");if(!a.finite)return invalid(MeshValidationError::NonFinite,"mesh has non-finite vertices");if(!a.indicesValid)return invalid(MeshValidationError::InvalidIndex,"mesh has invalid indices");if(a.degenerateFaces)return invalid(MeshValidationError::DegenerateFace,"mesh has degenerate faces");if(a.duplicateFaces)return invalid(MeshValidationError::DuplicateFace,"mesh has duplicate faces");if(a.boundaryEdges)return invalid(MeshValidationError::BoundaryEdge,"mesh is open");if(a.nonManifoldEdges)return invalid(MeshValidationError::NonManifoldEdge,"mesh has non-manifold edges");if(a.nonManifoldVertices)return invalid(MeshValidationError::NonManifoldVertex,"mesh has non-manifold vertices");if(a.selfIntersections)return invalid(MeshValidationError::SelfIntersection,"mesh self-intersects");if(a.connectedComponents!=1)return invalid(MeshValidationError::MultipleComponents,"mesh must have exactly one component");if(!a.consistentlyOriented)return invalid(MeshValidationError::InconsistentOrientation,"mesh orientation is inconsistent");if(a.signedVolume<=0)return invalid(MeshValidationError::NonPositiveVolume,"mesh volume must be positive");return{};}
MeshValidationResult validatePreparedMesh(const MeshAnalysisResult&a,bool allowMultiple){auto v=validateBooleanOperand(a);if(allowMultiple&&v.error==MeshValidationError::MultipleComponents)v={};return v;}
Point boundaryAttachmentDirection(const PrintMesh&m,const std::vector<std::uint32_t>&loop){if(loop.size()<3||m.vertices.empty())return{};Point n,c,insidePoint;for(std::size_t i=0;i<loop.size();++i){if(loop[i]>=m.vertices.size())return{};auto&a=m.vertices[loop[i]],&b=m.vertices[loop[(i+1)%loop.size()]];n.x+=(a.y-b.y)*(a.z+b.z);n.y+=(a.z-b.z)*(a.x+b.x);n.z+=(a.x-b.x)*(a.y+b.y);c.x+=a.x;c.y+=a.y;c.z+=a.z;}double l=std::sqrt(dot(n,n));if(l<E)return{};n={n.x/l,n.y/l,n.z/l};double count=double(loop.size());c={c.x/count,c.y/count,c.z/count};for(auto&p:m.vertices){insidePoint.x+=p.x;insidePoint.y+=p.y;insidePoint.z+=p.z;}count=double(m.vertices.size());insidePoint={insidePoint.x/count,insidePoint.y/count,insidePoint.z/count};if(dot(n,sub(c,insidePoint))<0)n={-n.x,-n.y,-n.z};return n;}
double maximumBoundsDeviation(const MeshBounds&a,const MeshBounds&b){if(!a.valid||!b.valid)return INFINITY;return std::max({std::abs(a.minimum.x-b.minimum.x),std::abs(a.minimum.y-b.minimum.y),std::abs(a.minimum.z-b.minimum.z),std::abs(a.maximum.x-b.maximum.x),std::abs(a.maximum.y-b.maximum.y),std::abs(a.maximum.z-b.maximum.z)});}
} // namespace PrintGeometry
