#include "LDrawObjWriter.h"
#include "print/PrintMeshConversion.h"
#include <QSaveFile>
#include <QTextStream>
#include <algorithm>
#include <cmath>

bool LDrawObjWriter::write(const LDrawGeometry::PartMesh& mesh,const QString& path,LDrawGeometry::Error* error)
{ return write(mesh,path,Options{},error); }

bool LDrawObjWriter::write(const LDrawGeometry::PartMesh& mesh,const QString& path,
                           const Options& options,LDrawGeometry::Error* error)
{
    Options effective=options;if(effective.ldrawId.isEmpty())effective.ldrawId=mesh.ldrawId;
    return write(PrintGeometry::PrintMeshConversion::fromPartMesh(mesh),path,effective,error);
}

bool LDrawObjWriter::write(const PrintGeometry::PrintMesh& mesh,const QString& path,const Options& options,LDrawGeometry::Error* error)
{
    const double scale=options.uniformScale;
    if(!(scale>0.0)||!std::isfinite(scale)||mesh.vertices.empty()||mesh.faces.empty()){if(error)*error={LDrawGeometry::ErrorCode::ExportFailed,"The selected geometry is invalid or empty.",path};return false;}
    QSaveFile file(path); if(!file.open(QIODevice::WriteOnly|QIODevice::Text)) {
        if(error) *error={LDrawGeometry::ErrorCode::ExportFailed,"The OBJ file could not be created.",path}; return false;
    }
    QTextStream out(&file); out.setRealNumberNotation(QTextStream::FixedNotation); out.setRealNumberPrecision(6);
    PrintGeometry::Point lo=mesh.vertices.front(),hi=lo;for(const auto&p:mesh.vertices){lo.x=std::min(lo.x,p.x);lo.y=std::min(lo.y,p.y);lo.z=std::min(lo.z,p.z);hi.x=std::max(hi.x,p.x);hi.y=std::max(hi.y,p.y);hi.z=std::max(hi.z,p.z);}
    out << "# Generated by BrickSuite\n";
    if (!options.partNumber.trimmed().isEmpty())
        out << "# BrickSuite Part: " << options.partNumber.simplified() << "\n";
    out << "# LDraw Model: " << options.ldrawId.simplified() << "\n";
    out << "# Geometry: " << options.geometryLabel << "\n";
    out << "# Scale: " << QString::number(scale * 100.0, 'f', 2) << "%\n";
    out << "# Dimensions: " << QString::number((hi.x-lo.x)*scale,'f',2)<<" x "<<QString::number((hi.y-lo.y)*scale,'f',2)<<" x "<<QString::number((hi.z-lo.z)*scale,'f',2)<<" mm\n";
    out << "# Units: millimetres; axes: X=LDraw X, Y=LDraw Z, Z=-LDraw Y\ng part\n";
    for(const auto&p:mesh.vertices)out<<"v "<<p.x*scale<<' '<<p.y*scale<<' '<<p.z*scale<<'\n';
    for(const auto&f:mesh.faces){if(f[0]>=mesh.vertices.size()||f[1]>=mesh.vertices.size()||f[2]>=mesh.vertices.size()){if(error)*error={LDrawGeometry::ErrorCode::ExportFailed,"The selected geometry contains an invalid face.",path};return false;}auto a=mesh.vertices[f[0]],b=mesh.vertices[f[1]],c=mesh.vertices[f[2]];double ux=b.x-a.x,uy=b.y-a.y,uz=b.z-a.z,vx=c.x-a.x,vy=c.y-a.y,vz=c.z-a.z,nx=uy*vz-uz*vy,ny=uz*vx-ux*vz,nz=ux*vy-uy*vx,l=std::sqrt(nx*nx+ny*ny+nz*nz);if(!(l>0)){if(error)*error={LDrawGeometry::ErrorCode::ExportFailed,"The selected geometry contains a degenerate face.",path};return false;}out<<"vn "<<nx/l<<' '<<ny/l<<' '<<nz/l<<'\n';}
    for(size_t i=0;i<mesh.faces.size();++i){const auto&f=mesh.faces[i];out<<"f "<<f[0]+1<<"//"<<i+1<<' '<<f[1]+1<<"//"<<i+1<<' '<<f[2]+1<<"//"<<i+1<<'\n';}
    if(out.status()!=QTextStream::Ok||!file.commit()){if(error)*error={LDrawGeometry::ErrorCode::ExportFailed,"The OBJ file could not be written completely.",path};return false;}return true;
}
