#include "LDrawObjWriter.h"
#include <QFile>
#include <QTextStream>

bool LDrawObjWriter::write(const LDrawGeometry::PartMesh& mesh,const QString& path,LDrawGeometry::Error* error)
{ return write(mesh,path,Options{},error); }

bool LDrawObjWriter::write(const LDrawGeometry::PartMesh& mesh,const QString& path,
                           const Options& options,LDrawGeometry::Error* error)
{
    const double scale = options.uniformScale > 0.0 ? options.uniformScale : 1.0;
    QFile file(path); if(!file.open(QIODevice::WriteOnly|QIODevice::Text|QIODevice::Truncate)) {
        if(error) *error={LDrawGeometry::ErrorCode::ExportFailed,"The OBJ file could not be created.",path}; return false;
    }
    QTextStream out(&file); out.setRealNumberNotation(QTextStream::FixedNotation); out.setRealNumberPrecision(6);
    const QVector3D dimensions = mesh.dimensionsMm() * float(scale);
    out << "# Generated by BrickSuite\n";
    if (!options.partNumber.trimmed().isEmpty())
        out << "# BrickSuite Part: " << options.partNumber.simplified() << "\n";
    out << "# LDraw Model: " << mesh.ldrawId.simplified() << "\n";
    out << "# Scale: " << QString::number(scale * 100.0, 'f', 2) << "%\n";
    out << "# Dimensions: " << QString::number(dimensions.x(), 'f', 2) << " x "
        << QString::number(dimensions.y(), 'f', 2) << " x "
        << QString::number(dimensions.z(), 'f', 2) << " mm\n";
    out << "# Units: millimetres; axes: X=LDraw X, Y=LDraw Z, Z=-LDraw Y\ng part\n";
    auto writePoint=[&](const QVector3D&p){out<<"v "<<p.x()*.4*scale<<' '<<p.z()*.4*scale<<' '<<-p.y()*.4*scale<<'\n';};
    for(const auto&t:mesh.triangles){writePoint(t.a);writePoint(t.b);writePoint(t.c);}
    for(const auto&t:mesh.triangles){const QVector3D n(t.normal.x(),t.normal.z(),-t.normal.y());out<<"vn "<<n.x()<<' '<<n.y()<<' '<<n.z()<<'\n';}
    for(int i=0;i<mesh.triangles.size();++i){int v=i*3+1,n=i+1;out<<"f "<<v<<"//"<<n<<' '<<v+1<<"//"<<n<<' '<<v+2<<"//"<<n<<'\n';}
    if(out.status()!=QTextStream::Ok){if(error)*error={LDrawGeometry::ErrorCode::ExportFailed,"The OBJ file could not be written completely.",path};return false;}
    return true;
}
