#include "ThreeMfWriter.h"
#include <lib3mf_implicit.hpp>
#include <QFile>
#include <QFileInfo>
#include <QSaveFile>
#include <QTemporaryFile>
#include <QColor>
#include <cmath>
bool ThreeMfWriter::write(const PrintGeometry::PrintMesh&m,const QString&path,const Options&o,QString*error){
 if(!(o.uniformScale>0)||!std::isfinite(o.uniformScale)||m.vertices.empty()||m.faces.empty()){if(error)*error="The selected geometry is invalid or empty.";return false;}
 if(!o.modelColor.isValid()){if(error)*error="The selected Model Color is invalid.";return false;}
 try{std::vector<Lib3MF::sPosition>v;v.reserve(m.vertices.size());for(auto&p:m.vertices){if(!std::isfinite(p.x)||!std::isfinite(p.y)||!std::isfinite(p.z)){if(error)*error="The selected geometry contains a non-finite vertex.";return false;}v.push_back({float(p.x*o.uniformScale),float(p.y*o.uniformScale),float(p.z*o.uniformScale)});}std::vector<Lib3MF::sTriangle>t;t.reserve(m.faces.size());for(auto&f:m.faces){if(f[0]>=v.size()||f[1]>=v.size()||f[2]>=v.size()){if(error)*error="The selected geometry contains an invalid face.";return false;}t.push_back({f[0],f[1],f[2]});}
 Lib3MF::CWrapper wrapper;auto model=wrapper.CreateModel();model->SetUnit(Lib3MF::eModelUnit::MilliMeter);auto object=model->AddMeshObject();object->SetName(o.objectName.toStdString());object->SetGeometry(v,t);auto colors=model->AddColorGroup();const Lib3MF::sColor color{quint8(o.modelColor.red()),quint8(o.modelColor.green()),quint8(o.modelColor.blue()),255};const auto defaultColorId=colors->AddColor(color);const auto triangleColorId=colors->AddColor(color);const auto colorResourceId=colors->GetUniqueResourceID();object->SetObjectLevelProperty(colorResourceId,defaultColorId);const Lib3MF::sTriangleProperties properties{colorResourceId,{triangleColorId,triangleColorId,triangleColorId}};for(Lib3MF_uint32 i=0;i<object->GetTriangleCount();++i)object->SetTriangleProperties(i,properties);model->AddBuildItem(std::static_pointer_cast<Lib3MF::CObject>(object),wrapper.GetIdentityTransform());auto meta=model->GetMetaDataGroup();meta->AddMetaData("https://rfstateside.com/bricksuite","Application","BrickSuite","string",false);if(!o.partIdentity.isEmpty())meta->AddMetaData("https://rfstateside.com/bricksuite","Part",o.partIdentity.toStdString(),"string",false);
 QTemporaryFile tmp(QFileInfo(path).absolutePath()+QStringLiteral("/.bricksuite-3mf-XXXXXX"));tmp.setAutoRemove(true);if(!tmp.open()){if(error)*error="A temporary 3MF file could not be created.";return false;}const QString tempName=tmp.fileName();tmp.close();model->QueryWriter("3mf")->WriteToFile(tempName.toStdString());QFile source(tempName);if(!source.open(QIODevice::ReadOnly)){if(error)*error="The generated 3MF package could not be read.";return false;}QSaveFile destination(path);if(!destination.open(QIODevice::WriteOnly)||destination.write(source.readAll())<0||!destination.commit()){if(error)*error="The 3MF file could not be committed to its destination.";return false;}return true;
 }catch(const std::exception&e){if(error)*error=QStringLiteral("The 3MF package could not be generated: %1").arg(QString::fromUtf8(e.what()));return false;}}
