#include "FrictionTechnicPinCalibrationArtifact.h"
#include "../print/FrictionTechnicPinSemantic.h"
#include "../print/FunctionalOperandRegenerator.h"
#include "../print/McutMeshBooleanService.h"
#include "../print/PrintMeshAnalysis.h"
namespace PrintGeometry { namespace {PrintMesh box(double x0,double x1,double y0,double y1,double z0,double z1){PrintMesh m;m.vertices={{x0,y0,z0},{x1,y0,z0},{x1,y1,z0},{x0,y1,z0},{x0,y0,z1},{x1,y0,z1},{x1,y1,z1},{x0,y1,z1}};m.faces={{0,2,1},{0,3,2},{4,5,6},{4,6,7},{0,1,5},{0,5,4},{1,2,6},{1,6,5},{2,3,7},{2,7,6},{3,0,4},{3,4,7}};return m;}}
QString FrictionTechnicPinCalibrationArtifact::artifactIdentity(){return "friction-technic-pin-confric5-ridge-perpendicular-coarse-v1";}
QVector<double> FrictionTechnicPinCalibrationArtifact::ridgeEnvelopeCorrectionsMillimetres(){return {-.10,-.05,0,.05,.10,.15,.20};}
FrictionTechnicPinCalibrationResult FrictionTechnicPinCalibrationArtifact::generate(){FrictionTechnicPinCalibrationArtifactDefinition d;d.artifactIdentity=artifactIdentity();return generate(FrictionTechnicPinSemantic::canonicalPrototype(),d);}
FrictionTechnicPinCalibrationResult FrictionTechnicPinCalibrationArtifact::generate(const FunctionalFeature&prototype,const FrictionTechnicPinCalibrationArtifactDefinition&d){FrictionTechnicPinCalibrationResult r;r.artifactIdentity=d.artifactIdentity;r.parentArtifactIdentity=d.parentArtifactIdentity;r.orientationIdentity="flat-base-friction-pin-axis-perpendicular-v1";r.regenerationPrototype=prototype;if(r.artifactIdentity.isEmpty()||d.candidateCount<3||d.candidateCount%2==0||d.candidateSpacingMillimetres<=0){r.diagnostic="The friction-pin artifact definition is invalid.";return r;}McutMeshBooleanService boolean;const double width=16.0*d.candidateCount;r.mesh=box(0,width,0,16,0,3);auto marker=boolean.unite(r.mesh,box(0,4,15,20,0,2.5));if(!marker.ok()){r.diagnostic="Candidate #1 marker could not be joined.";return r;}r.mesh=std::move(marker.mesh);for(int i=0;i<d.candidateCount;++i){const double correction=d.centerRidgeEnvelopeCorrectionMillimetres+(i-d.candidateCount/2)*d.candidateSpacingMillimetres;auto f=r.regenerationPrototype;f.stableIdentity=QString("%1:candidate-%2").arg(r.artifactIdentity).arg(i+1);f.frame.origin={8.0+16.0*i,8,2.9};const auto pin=FunctionalOperandRegenerator::regenerateFrictionPin(f,{correction});if(!pin.ok()){r.diagnostic=pin.diagnostic;return r;}auto joined=boolean.unite(r.mesh,pin.mesh);if(!joined.ok()){r.diagnostic=QString("Friction-pin candidate %1 could not be joined.").arg(i+1);return r;}r.mesh=std::move(joined.mesh);FitCalibrationCandidate c;c.index=i+1;c.diameterCorrectionMillimetres=correction;c.functionalDiameterMillimetres=5.0+correction;r.candidates.push_back(c);}r.analysis=analyzeSource(r.mesh);const auto valid=validatePreparedMesh(r.analysis);if(!valid.ok()){r.diagnostic=QString("Friction-pin artifact failed validation: %1").arg(QString::fromStdString(valid.message));return r;}r.ok=true;r.diagnostic=QString("%1 independent confric5 friction-ridge envelope candidates generated with a Candidate #1-side marker.").arg(d.candidateCount);return r;}
FitCalibrationExperiment FrictionTechnicPinCalibrationArtifact::observationTemplate(const FrictionTechnicPinCalibrationResult&r){FitCalibrationExperiment e;e.artifactIdentity=r.artifactIdentity;e.parentArtifactIdentity=r.parentArtifactIdentity;e.featureFamily="FrictionTechnicPin";e.featureRole="male";e.modeledOrientationIdentity=r.orientationIdentity;e.candidateSpacingMillimetres=.05;e.regenerationPrototype=r.regenerationPrototype;e.hasRegenerationPrototype=true;e.candidates=r.candidates;e.process.actualPrintedOrientation=FitPrintedOrientation::FeatureAxisPerpendicularToBuildPlate;e.process.orientationNotes="Print the flat base on the build plate; pin axes are perpendicular. Candidate #1 is beside the raised side marker. Test each candidate in genuine LEGO Technic holes.";e.process.dimensionalCompensationNotes="Print at 100% scale and record slicer dimensional compensation settings.";return e;}
}
