#include "FrictionlessTechnicPinCalibrationArtifact.h"
#include "../print/FrictionlessTechnicPinSemantic.h"
#include "../print/FunctionalOperandRegenerator.h"
#include "../print/McutMeshBooleanService.h"
#include "../print/PrintMeshAnalysis.h"
namespace PrintGeometry { namespace {PrintMesh box(double x0,double x1,double y0,double y1,double z0,double z1){PrintMesh m;m.vertices={{x0,y0,z0},{x1,y0,z0},{x1,y1,z0},{x0,y1,z0},{x0,y0,z1},{x1,y0,z1},{x1,y1,z1},{x0,y1,z1}};m.faces={{0,2,1},{0,3,2},{4,5,6},{4,6,7},{0,1,5},{0,5,4},{1,2,6},{1,6,5},{2,3,7},{2,7,6},{3,0,4},{3,4,7}};return m;}}
QString FrictionlessTechnicPinCalibrationArtifact::artifactIdentity(){return "frictionless-technic-pin-perpendicular-coarse-v1";}
QVector<double> FrictionlessTechnicPinCalibrationArtifact::diameterCorrectionsMillimetres(){return {-.3,-.2,-.1,0,.1,.2,.3};}
FrictionlessTechnicPinCalibrationResult FrictionlessTechnicPinCalibrationArtifact::generate(){FrictionlessTechnicPinCalibrationResult r;r.artifactIdentity=artifactIdentity();r.orientationIdentity="flat-base-pin-axis-perpendicular-v1";r.regenerationPrototype=FrictionlessTechnicPinSemantic::canonicalPrototype();McutMeshBooleanService boolean;r.mesh=box(0,112,0,16,0,3);const auto corrections=diameterCorrectionsMillimetres();for(int i=0;i<corrections.size();++i){auto f=r.regenerationPrototype;f.stableIdentity=QString("%1:candidate-%2").arg(r.artifactIdentity).arg(i+1);f.frame.origin={8.0+16.0*i,8,2.9};const auto pin=FunctionalOperandRegenerator::regenerateFrictionlessPin(f,{corrections[i]});if(!pin.ok()){r.diagnostic=pin.diagnostic;return r;}auto joined=boolean.unite(r.mesh,pin.mesh);if(!joined.ok()){r.diagnostic=QString("Pin candidate %1 could not be joined.").arg(i+1);return r;}r.mesh=std::move(joined.mesh);FitCalibrationCandidate c;c.index=i+1;c.diameterCorrectionMillimetres=corrections[i];c.functionalDiameterMillimetres=6.4+corrections[i];r.candidates.push_back(c);}r.analysis=analyzeSource(r.mesh);const auto valid=validatePreparedMesh(r.analysis);if(!valid.ok()){r.diagnostic=QString("Frictionless-pin artifact failed validation: %1").arg(QString::fromStdString(valid.message));return r;}r.ok=true;r.diagnostic="Seven independent frictionless Technic-pin envelope candidates generated at fixed 100% scale.";return r;}
FitCalibrationExperiment FrictionlessTechnicPinCalibrationArtifact::observationTemplate(const FrictionlessTechnicPinCalibrationResult&r){FitCalibrationExperiment e;e.artifactIdentity=r.artifactIdentity;e.featureFamily="FrictionlessTechnicPin";e.featureRole="male";e.modeledOrientationIdentity=r.orientationIdentity;e.candidateSpacingMillimetres=.1;e.regenerationPrototype=r.regenerationPrototype;e.hasRegenerationPrototype=true;e.candidates=r.candidates;e.process.actualPrintedOrientation=FitPrintedOrientation::FeatureAxisPerpendicularToBuildPlate;e.process.orientationNotes="Print the flat base on the build plate; pin axes are perpendicular. Test each candidate in the same genuine LEGO Technic hole.";e.process.dimensionalCompensationNotes="Print at 100% scale and record slicer dimensional compensation settings.";return e;}
}
