#include "RoundTechnicCalibrationArtifact.h"
#include "../print/McutMeshBooleanService.h"
#include "../print/PrintMeshAnalysis.h"
#include <QPointF>
#include <algorithm>
#include <cmath>

namespace PrintGeometry { namespace {
PrintMesh keyedBody(int count){PrintMesh mesh;const double width=12.0*count+8.0;const QVector<QPointF> profile{{0,0},{width,0},{width,14},{3,14},{0,11}};for(double y:{0.0,8.0})for(const auto&p:profile)mesh.vertices.push_back({p.x(),y,p.y()});const std::uint32_t n=std::uint32_t(profile.size());for(std::uint32_t i=1;i+1<n;++i){mesh.faces.push_back({0,i+1,i});mesh.faces.push_back({n,n+i,n+i+1});}for(std::uint32_t i=0;i<n;++i){const auto next=(i+1)%n;mesh.faces.push_back({i,next,n+i});mesh.faces.push_back({next,n+next,n+i});}if(analyzeSource(mesh).signedVolume<0)for(auto&face:mesh.faces)std::swap(face[1],face[2]);return mesh;}
bool sameContract(const FunctionalFeature&f){return f.family==FunctionalInterfaceFamily::RoundTechnicPassage&&f.role==FunctionalInterfaceRole::Female&&f.materialSide==FunctionalMaterialSide::EmptyInsideMaterialOutside&&f.eligibility==FunctionalEligibility::Eligible&&f.confidence==SemanticConfidence::HighConfidence&&f.operandAction==FunctionalOperandAction::Subtract&&f.radialProfile.size()==6;}
}
QString RoundTechnicCalibrationArtifact::artifactIdentity(){return QStringLiteral("round-technic-female-horizontal-v1");}
QString RoundTechnicCalibrationArtifact::orientationIdentity(){return QStringLiteral("flat-base-horizontal-axis-y-v1");}
QString RoundTechnicCalibrationArtifact::parallelArtifactIdentity(){return QStringLiteral("round-technic-female-parallel-coarse-v1");}
RoundTechnicCalibrationArtifactDefinition RoundTechnicCalibrationArtifact::parallelCoarseDefinition(){RoundTechnicCalibrationArtifactDefinition d;d.artifactIdentity=parallelArtifactIdentity();d.centerDiameterCorrectionMillimetres=.30;d.candidateSpacingMillimetres=.10;d.candidateCount=7;d.printedOrientation=FitPrintedOrientation::FeatureAxisParallelToBuildPlate;return d;}
FunctionalFeature RoundTechnicCalibrationArtifact::canonicalPrototype(){FunctionalFeature f;f.stableIdentity="round-technic-female-calibration-prototype";f.family=FunctionalInterfaceFamily::RoundTechnicPassage;f.role=FunctionalInterfaceRole::Female;f.materialSide=FunctionalMaterialSide::EmptyInsideMaterialOutside;f.eligibility=FunctionalEligibility::Eligible;f.confidence=SemanticConfidence::HighConfidence;f.frame={{0,0,0},{0,1,0},{1,0,0},{0,0,-1},false};f.nominalRadiusMillimetres=2.4;f.nominalDiameterMillimetres=4.8;f.nominalAxialExtentMillimetres=8;f.nominalEngagementExtentMillimetres=6.4;f.radialProfile={{-4.1,3.2},{-3.2,3.2},{-3.2,2.4},{3.2,2.4},{3.2,3.2},{4.1,3.2}};f.operandAction=FunctionalOperandAction::Subtract;f.constructionRecipe="round-through-passage-v1";f.governingOperandIdentity="round-technic-female-calibration-prototype:operand";f.evidenceContract="official-ldraw-peghole-pair-v1";return f;}
QVector<double> RoundTechnicCalibrationArtifact::diameterCorrectionsMillimetres(){return {-.30,-.20,-.10,0,.10,.20,.30};}
RoundTechnicCalibrationArtifactResult RoundTechnicCalibrationArtifact::generate(const FunctionalFeature&p){RoundTechnicCalibrationArtifactDefinition d;d.artifactIdentity=artifactIdentity();return generate(p,d);}
RoundTechnicCalibrationArtifactResult RoundTechnicCalibrationArtifact::generate(const FunctionalFeature&prototype,const RoundTechnicCalibrationArtifactDefinition&d){RoundTechnicCalibrationArtifactResult r;r.artifactIdentity=d.artifactIdentity;r.orientationIdentity=orientationIdentity();r.regenerationPrototype=prototype;if(!sameContract(prototype)){r.diagnostic="The prototype is not an eligible female round Technic passage contract.";return r;}if(d.artifactIdentity.isEmpty()||d.candidateCount<3||d.candidateCount>9||d.candidateCount%2==0||!std::isfinite(d.centerDiameterCorrectionMillimetres)||!std::isfinite(d.candidateSpacingMillimetres)||d.candidateSpacingMillimetres<=0){r.diagnostic="The calibration artifact definition is invalid; use an odd candidate count from 3 through 9 and positive spacing.";return r;}McutMeshBooleanService booleans;PrintMesh body=keyedBody(d.candidateCount);if(!validateBooleanOperand(analyzeSource(body)).ok()){r.diagnostic="The calibration body is invalid.";return r;}const int half=d.candidateCount/2;for(int i=0;i<d.candidateCount;++i){const double correction=d.centerDiameterCorrectionMillimetres+(i-half)*d.candidateSpacingMillimetres;FunctionalFeature candidate=prototype;candidate.stableIdentity=QStringLiteral("%1:candidate-%2").arg(d.artifactIdentity).arg(i+1);candidate.frame.origin={8.0+12.0*i,4.0,7.0};candidate.frame.axis={0,1,0};candidate.frame.profileU={1,0,0};candidate.frame.profileV={0,0,-1};candidate.frame.mirrored=false;const auto regenerated=FunctionalOperandRegenerator::regenerate(candidate,{correction});if(!regenerated.ok()){r.diagnostic=QStringLiteral("Candidate %1 could not be regenerated: %2").arg(i+1).arg(regenerated.diagnostic);return r;}auto subtraction=booleans.subtract(body,regenerated.mesh);if(!subtraction.ok()){r.diagnostic=QStringLiteral("Candidate %1 could not be composed into the artifact.").arg(i+1);return r;}body=std::move(subtraction.mesh);FitCalibrationCandidate record;record.index=i+1;record.diameterCorrectionMillimetres=correction;record.functionalDiameterMillimetres=regenerated.resultingGoverningRadiusMillimetres*2.0;r.candidates.push_back(record);}r.mesh=std::move(body);r.analysis=analyzeSource(r.mesh);const auto validation=validatePreparedMesh(r.analysis);if(!validation.ok()){r.diagnostic=QStringLiteral("The composed calibration artifact failed validation: %1").arg(QString::fromStdString(validation.message));return r;}r.ok=true;r.diagnostic="Calibration artifact generated at fixed 100% physical scale.";return r;}
FitCalibrationExperiment RoundTechnicCalibrationArtifact::observationTemplate(const RoundTechnicCalibrationArtifactResult&a){RoundTechnicCalibrationArtifactDefinition d;d.artifactIdentity=a.artifactIdentity;return observationTemplate(a,d);}
FitCalibrationExperiment RoundTechnicCalibrationArtifact::observationTemplate(const RoundTechnicCalibrationArtifactResult&a,const RoundTechnicCalibrationArtifactDefinition&d){FitCalibrationExperiment e;e.artifactIdentity=a.artifactIdentity;e.parentArtifactIdentity=d.parentArtifactIdentity;e.featureFamily="RoundTechnicPassage";e.featureRole="female";e.modeledOrientationIdentity=a.orientationIdentity;e.centerDiameterCorrectionMillimetres=d.centerDiameterCorrectionMillimetres;e.candidateSpacingMillimetres=d.candidateSpacingMillimetres;e.regenerationPrototype=a.regenerationPrototype;e.hasRegenerationPrototype=true;e.candidates=a.candidates;e.process.actualPrintedOrientation=d.printedOrientation;e.process.orientationNotes=d.printedOrientation==FitPrintedOrientation::FeatureAxisParallelToBuildPlate?QStringLiteral("Print the broad flat base on the build plate; every Technic passage axis is parallel to the build plate."):QStringLiteral("Record the actual feature-axis orientation used in the slicer; modeled orientation is not manufacturing evidence.");e.process.dimensionalCompensationNotes="Print at 100% scale and record any slicer dimensional compensation settings.";return e;}
} // namespace PrintGeometry
