#include "StudReceivingCalibrationArtifact.h"
#include "../print/McutMeshBooleanService.h"
#include "../print/PrintMeshAnalysis.h"
#include <algorithm>

namespace PrintGeometry { namespace {
PrintMesh box(double x0,double x1,double y0,double y1,double z0,double z1){PrintMesh m;m.vertices={{x0,y0,z0},{x1,y0,z0},{x1,y1,z0},{x0,y1,z0},{x0,y0,z1},{x1,y0,z1},{x1,y1,z1},{x0,y1,z1}};m.faces={{0,2,1},{0,3,2},{4,5,6},{4,6,7},{0,1,5},{0,5,4},{1,2,6},{1,6,5},{2,3,7},{2,7,6},{3,0,4},{3,4,7}};return m;}
}
FunctionalFeature StudReceivingCalibrationArtifact::canonicalPrototype(){FunctionalFeature f;f.stableIdentity="official-stud4-tube-wall-cell-prototype";f.family=FunctionalInterfaceFamily::StudReceivingClutch;f.role=FunctionalInterfaceRole::Female;f.materialSide=FunctionalMaterialSide::MaterialInside;f.eligibility=FunctionalEligibility::Eligible;f.confidence=SemanticConfidence::HighConfidence;f.frame={{0,0,0},{0,0,1},{1,0,0},{0,1,0},false};f.nominalRadiusMillimetres=3.2;f.nominalDiameterMillimetres=6.4;f.nominalAxialExtentMillimetres=3.2;f.nominalEngagementExtentMillimetres=3.2;f.protectedInnerRadiusMillimetres=2.4;f.operandAction=FunctionalOperandAction::Unite;f.constructionRecipe="stud-receiving-tube-wall-cell-v1";f.evidenceContract="official-ldraw-stud4-tube-wall-cell-v1";f.governingOperandIdentity=f.stableIdentity+":operand";f.radialProfile={{0,3.2},{3.2,3.2}};return f;}
QString StudReceivingCalibrationArtifact::artifactIdentity(){return "stud-receiving-clutch-tube-wall-cell-perpendicular-v1";}
QString StudReceivingCalibrationArtifact::orientationIdentity(){return "flat-base-receiving-axis-perpendicular-v1";}
QVector<double> StudReceivingCalibrationArtifact::diameterCorrectionsMillimetres(){return {-.3,-.2,-.1,0,.1,.2,.3};}
FitCalibrationExperiment StudReceivingCalibrationArtifact::observationTemplate(const StudReceivingCalibrationArtifactResult&a){StudReceivingCalibrationArtifactDefinition d;d.artifactIdentity=a.artifactIdentity;d.parentArtifactIdentity=a.parentArtifactIdentity;return observationTemplate(a,d);}
StudReceivingCalibrationArtifactResult StudReceivingCalibrationArtifact::generate(){StudReceivingCalibrationArtifactDefinition d;d.artifactIdentity=artifactIdentity();return generate(canonicalPrototype(),d);}
StudReceivingCalibrationArtifactResult StudReceivingCalibrationArtifact::generate(const FunctionalFeature&prototype,const StudReceivingCalibrationArtifactDefinition&d){StudReceivingCalibrationArtifactResult r;r.artifactIdentity=d.artifactIdentity;r.parentArtifactIdentity=d.parentArtifactIdentity;r.orientationIdentity=orientationIdentity();r.regenerationPrototype=prototype;if(prototype.family!=FunctionalInterfaceFamily::StudReceivingClutch||prototype.constructionRecipe!="stud-receiving-tube-wall-cell-v1"||d.artifactIdentity.isEmpty()||d.candidateCount<3||d.candidateCount>9||d.candidateCount%2==0||d.candidateSpacingMillimetres<=0){r.diagnostic="The TubeWallCell artifact definition or retained contract is invalid.";return r;}McutMeshBooleanService b;PrintMesh body=box(0,18*d.candidateCount,0,16,0,4.8);const int half=d.candidateCount/2;for(int i=0;i<d.candidateCount;++i){const double correction=d.centerDiameterCorrectionMillimetres+(i-half)*d.candidateSpacingMillimetres,cx=9+18*i;auto cut=b.subtract(body,box(cx-6.4,cx+6.4,1.6,14.4,1.6,5.0));if(!cut.ok()){r.diagnostic=QString("Receiving-cell cavity %1 failed.").arg(i+1);return r;}body=std::move(cut.mesh);auto feature=prototype;feature.stableIdentity=QString("%1:candidate-%2").arg(r.artifactIdentity).arg(i+1);feature.frame.origin={cx,8,1.6};const auto tube=FunctionalOperandRegenerator::regenerateReceivingTube(feature,{correction});if(!tube.ok()){r.diagnostic=tube.diagnostic;return r;}auto joined=b.unite(body,tube.mesh);if(!joined.ok()){r.diagnostic=QString("Receiving tube %1 could not be joined.").arg(i+1);return r;}body=std::move(joined.mesh);FitCalibrationCandidate c;c.index=i+1;c.diameterCorrectionMillimetres=correction;c.functionalDiameterMillimetres=6.4+correction;r.candidates.push_back(c);}r.mesh=std::move(body);r.analysis=analyzeSource(r.mesh);const auto valid=validatePreparedMesh(r.analysis);if(!valid.ok()){r.diagnostic=QString("TubeWallCell artifact failed validation: %1").arg(QString::fromStdString(valid.message));return r;}r.ok=true;r.diagnostic=QString("%1 independent TubeWallCell candidates generated at fixed 100% scale.").arg(d.candidateCount);return r;}
FitCalibrationExperiment StudReceivingCalibrationArtifact::observationTemplate(const StudReceivingCalibrationArtifactResult&a,const StudReceivingCalibrationArtifactDefinition&d){FitCalibrationExperiment e;e.artifactIdentity=a.artifactIdentity;e.parentArtifactIdentity=d.parentArtifactIdentity;e.featureFamily="StudReceivingClutch";e.featureRole="female";e.modeledOrientationIdentity=a.orientationIdentity;e.centerDiameterCorrectionMillimetres=d.centerDiameterCorrectionMillimetres;e.candidateSpacingMillimetres=d.candidateSpacingMillimetres;e.regenerationPrototype=a.regenerationPrototype;e.hasRegenerationPrototype=true;e.candidates=a.candidates;e.process.actualPrintedOrientation=FitPrintedOrientation::FeatureAxisPerpendicularToBuildPlate;e.process.orientationNotes="Print the flat base on the build plate; test each receiving cell with a genuine LEGO stud in the normal tube-and-wall position, not in the center bore.";e.process.dimensionalCompensationNotes="Print at 100% scale and record all slicer dimensional compensation settings.";return e;}
}
