#include "TechnicAxleHoleCalibrationArtifact.h"

#include "../print/FunctionalOperandRegenerator.h"
#include "../print/McutMeshBooleanService.h"
#include "../print/PrintMeshAnalysis.h"
#include "../print/TechnicAxleSemantic.h"

namespace PrintGeometry { namespace {
PrintMesh box(double x0,double x1,double y0,double y1,double z0,double z1){PrintMesh m;m.vertices={{x0,y0,z0},{x1,y0,z0},{x1,y1,z0},{x0,y1,z0},{x0,y0,z1},{x1,y0,z1},{x1,y1,z1},{x0,y1,z1}};m.faces={{0,2,1},{0,3,2},{4,5,6},{4,6,7},{0,1,5},{0,5,4},{1,2,6},{1,6,5},{2,3,7},{2,7,6},{3,0,4},{3,4,7}};return m;}
}

QString TechnicAxleHoleCalibrationArtifact::artifactIdentity(){return QStringLiteral("technic-axle-hole-tip-clearance-perpendicular-coarse-v1");}
QVector<double> TechnicAxleHoleCalibrationArtifact::tipToTipCorrectionsMillimetres(){return {0,.05,.10,.15,.20,.25,.30};}
TechnicAxleHoleCalibrationResult TechnicAxleHoleCalibrationArtifact::generate(){TechnicAxleHoleCalibrationArtifactDefinition d;d.artifactIdentity=artifactIdentity();return generate(TechnicAxleSemantic::canonicalAxleHolePrototype(),d);}
TechnicAxleHoleCalibrationResult TechnicAxleHoleCalibrationArtifact::generate(const FunctionalFeature&prototype,const TechnicAxleHoleCalibrationArtifactDefinition&d){TechnicAxleHoleCalibrationResult r;r.artifactIdentity=d.artifactIdentity;r.parentArtifactIdentity=d.parentArtifactIdentity;r.orientationIdentity=QStringLiteral("flat-base-technic-axle-hole-axis-perpendicular-v1");r.regenerationPrototype=prototype;if(r.artifactIdentity.isEmpty()||d.candidateCount<3||d.candidateCount>9||d.candidateCount%2==0||d.candidateSpacingMillimetres<=0){r.diagnostic=QStringLiteral("The Technic axle-hole artifact definition is invalid.");return r;}constexpr double spacing=16.0,depth=8.0;McutMeshBooleanService boolean;r.mesh=box(0,spacing*d.candidateCount,0,16,0,depth);auto marked=boolean.unite(r.mesh,box(0,4,15,20,0,2.5));if(!marked.ok()){r.diagnostic=QStringLiteral("Candidate #1 marker could not be joined.");return r;}r.mesh=std::move(marked.mesh);for(int i=0;i<d.candidateCount;++i){const double correction=d.centerTipToTipCorrectionMillimetres+(i-d.candidateCount/2)*d.candidateSpacingMillimetres;auto feature=prototype;feature.stableIdentity=QStringLiteral("%1:candidate-%2").arg(r.artifactIdentity).arg(i+1);feature.frame.origin={8.0+spacing*i,8,-.1};feature.nominalAxialExtentMillimetres=depth+.2;feature.nominalEngagementExtentMillimetres=depth;const auto opening=FunctionalOperandRegenerator::regenerateTechnicAxleProfile(feature,{correction});if(!opening.ok()){r.diagnostic=opening.diagnostic;return r;}auto cut=boolean.subtract(r.mesh,opening.mesh);if(!cut.ok()){r.diagnostic=QStringLiteral("Technic axle-hole candidate %1 could not be cut.").arg(i+1);return r;}r.mesh=std::move(cut.mesh);FitCalibrationCandidate candidate;candidate.index=i+1;candidate.diameterCorrectionMillimetres=correction;candidate.functionalDiameterMillimetres=4.8+correction;r.candidates.push_back(candidate);}r.analysis=analyzeSource(r.mesh);const auto valid=validatePreparedMesh(r.analysis);if(!valid.ok()){r.diagnostic=QStringLiteral("Technic axle-hole artifact failed validation: %1").arg(QString::fromStdString(valid.message));return r;}r.ok=true;r.diagnostic=QStringLiteral("%1 ordinary Technic axle-hole tip-to-tip clearance candidates generated with protected cross-arm geometry, 8.0 mm engagement, and a Candidate #1-side marker.").arg(d.candidateCount);return r;}
FitCalibrationExperiment TechnicAxleHoleCalibrationArtifact::observationTemplate(const TechnicAxleHoleCalibrationResult&r,const TechnicAxleHoleCalibrationArtifactDefinition&definition){FitCalibrationExperiment e;e.artifactIdentity=r.artifactIdentity;e.parentArtifactIdentity=r.parentArtifactIdentity;e.featureFamily=QStringLiteral("TechnicAxleHole");e.featureRole=QStringLiteral("female");e.modeledOrientationIdentity=r.orientationIdentity;e.centerDiameterCorrectionMillimetres=definition.centerTipToTipCorrectionMillimetres;e.candidateSpacingMillimetres=definition.candidateSpacingMillimetres;e.regenerationPrototype=r.regenerationPrototype;e.hasRegenerationPrototype=true;e.candidates=r.candidates;e.process.actualPrintedOrientation=FitPrintedOrientation::FeatureAxisPerpendicularToBuildPlate;e.process.orientationNotes=QStringLiteral("Print the flat base on the build plate with axle-hole axes perpendicular. Candidate #1 is beside the raised side marker. Test with two ordinary genuine LEGO axles, excluding reduced, rounded, sliding, D-axle, and other specialized variants.");e.process.dimensionalCompensationNotes=QStringLiteral("Print at 100% scale and record slicer dimensional compensation settings.");return e;}

QString TechnicAxleHoleArmWidthCalibrationArtifact::artifactIdentity(){return QStringLiteral("technic-axle-hole-arm-width-perpendicular-coarse-v2");}
TechnicAxleHoleCalibrationResult TechnicAxleHoleArmWidthCalibrationArtifact::generate(){auto prototype=TechnicAxleSemantic::canonicalAxleHolePrototype();prototype.stableIdentity=QStringLiteral("official-technic-axle-hole-arm-width-prototype-v2");prototype.constructionRecipe=QStringLiteral("technic-axle-hole-arm-width-clearance-v2");prototype.evidenceContract=QStringLiteral("official-ldraw-axlehole-arm-width-clearance-v2");prototype.governingOperandIdentity=prototype.stableIdentity+QStringLiteral(":operand");TechnicAxleHoleArmWidthArtifactDefinition d;d.artifactIdentity=artifactIdentity();d.parentArtifactIdentity=QStringLiteral("technic-axle-hole-tip-clearance-perpendicular-coarse-extension-v2");return generate(prototype,d);}
TechnicAxleHoleCalibrationResult TechnicAxleHoleArmWidthCalibrationArtifact::generate(const FunctionalFeature&prototype,const TechnicAxleHoleArmWidthArtifactDefinition&d){TechnicAxleHoleCalibrationResult r;r.artifactIdentity=d.artifactIdentity;r.parentArtifactIdentity=d.parentArtifactIdentity;r.orientationIdentity=QStringLiteral("flat-base-technic-axle-hole-axis-perpendicular-v1");r.regenerationPrototype=prototype;if(r.artifactIdentity.isEmpty()||d.candidateCount<3||d.candidateCount>9||d.candidateCount%2==0||d.candidateSpacingMillimetres<=0){r.diagnostic=QStringLiteral("The Technic axle-hole arm-width artifact definition is invalid.");return r;}constexpr double spacing=16.0,depth=8.0;McutMeshBooleanService boolean;r.mesh=box(0,spacing*d.candidateCount,0,16,0,depth);auto marked=boolean.unite(r.mesh,box(0,4,15,20,0,2.5));if(!marked.ok()){r.diagnostic=QStringLiteral("Candidate #1 marker could not be joined.");return r;}r.mesh=std::move(marked.mesh);for(int i=0;i<d.candidateCount;++i){const double correction=d.centerArmWidthCorrectionMillimetres+(i-d.candidateCount/2)*d.candidateSpacingMillimetres;auto feature=prototype;feature.stableIdentity=QStringLiteral("%1:candidate-%2").arg(r.artifactIdentity).arg(i+1);feature.frame.origin={8.0+spacing*i,8,-.1};feature.nominalAxialExtentMillimetres=depth+.2;feature.nominalEngagementExtentMillimetres=depth;const auto opening=FunctionalOperandRegenerator::regenerateTechnicAxleHoleArmWidth(feature,{correction,d.fixedTipToTipCorrectionMillimetres});if(!opening.ok()){r.diagnostic=opening.diagnostic;return r;}auto cut=boolean.subtract(r.mesh,opening.mesh);if(!cut.ok()){r.diagnostic=QStringLiteral("Technic axle-hole arm-width candidate %1 could not be cut.").arg(i+1);return r;}r.mesh=std::move(cut.mesh);FitCalibrationCandidate candidate;candidate.index=i+1;candidate.diameterCorrectionMillimetres=correction;candidate.functionalDiameterMillimetres=1.6+correction;r.candidates.push_back(candidate);}r.analysis=analyzeSource(r.mesh);const auto valid=validatePreparedMesh(r.analysis);if(!valid.ok()){r.diagnostic=QStringLiteral("Technic axle-hole arm-width artifact failed validation: %1").arg(QString::fromStdString(valid.message));return r;}r.ok=true;r.diagnostic=QStringLiteral("%1 axle-hole arm-width candidates generated with tip-to-tip fixed at %2 mm, protected 8.0 mm engagement, and a Candidate #1-side marker.").arg(d.candidateCount).arg(4.8+d.fixedTipToTipCorrectionMillimetres,0,'f',2);return r;}
FitCalibrationExperiment TechnicAxleHoleArmWidthCalibrationArtifact::observationTemplate(const TechnicAxleHoleCalibrationResult&r,const TechnicAxleHoleArmWidthArtifactDefinition&d){FitCalibrationExperiment e;e.artifactIdentity=r.artifactIdentity;e.parentArtifactIdentity=r.parentArtifactIdentity;e.featureFamily=QStringLiteral("TechnicAxleHole");e.featureRole=QStringLiteral("female");e.modeledOrientationIdentity=r.orientationIdentity;e.centerDiameterCorrectionMillimetres=d.centerArmWidthCorrectionMillimetres;e.fixedDiameterCorrectionMillimetres=d.fixedTipToTipCorrectionMillimetres;e.candidateSpacingMillimetres=d.candidateSpacingMillimetres;e.regenerationPrototype=r.regenerationPrototype;e.hasRegenerationPrototype=true;e.candidates=r.candidates;e.process.actualPrintedOrientation=FitPrintedOrientation::FeatureAxisPerpendicularToBuildPlate;e.process.orientationNotes=QStringLiteral("Arm-width clearance experiment: print perpendicular with Candidate #1 beside the raised marker. Tip-to-tip is fixed at 5.10 mm; test with two ordinary genuine LEGO axles for arm interference, seating, play, retention, removal, and stress.");e.process.dimensionalCompensationNotes=QStringLiteral("Print at 100% scale and record slicer dimensional compensation settings.");return e;}

} // namespace PrintGeometry
