#include "TechnicAxleCalibrationArtifact.h"

#include "../print/FunctionalOperandRegenerator.h"
#include "../print/McutMeshBooleanService.h"
#include "../print/PrintMeshAnalysis.h"
#include "../print/TechnicAxleSemantic.h"

namespace PrintGeometry { namespace {
PrintMesh box(double x0,double x1,double y0,double y1,double z0,double z1){PrintMesh m;m.vertices={{x0,y0,z0},{x1,y0,z0},{x1,y1,z0},{x0,y1,z0},{x0,y0,z1},{x1,y0,z1},{x1,y1,z1},{x0,y1,z1}};m.faces={{0,2,1},{0,3,2},{4,5,6},{4,6,7},{0,1,5},{0,5,4},{1,2,6},{1,6,5},{2,3,7},{2,7,6},{3,0,4},{3,4,7}};return m;}
}
QString TechnicAxleCalibrationArtifact::artifactIdentity(){return QStringLiteral("technic-axle-tip-envelope-perpendicular-coarse-v1");}
QVector<double> TechnicAxleCalibrationArtifact::tipToTipCorrectionsMillimetres(){return {-.15,-.10,-.05,0,.05,.10,.15};}
TechnicAxleCalibrationResult TechnicAxleCalibrationArtifact::generate(){TechnicAxleCalibrationArtifactDefinition d;d.artifactIdentity=artifactIdentity();return generate(TechnicAxleSemantic::canonicalAxlePrototype(),d);}
TechnicAxleCalibrationResult TechnicAxleCalibrationArtifact::generate(const FunctionalFeature&prototype,const TechnicAxleCalibrationArtifactDefinition&d){TechnicAxleCalibrationResult r;r.artifactIdentity=d.artifactIdentity;r.parentArtifactIdentity=d.parentArtifactIdentity;r.orientationIdentity=QStringLiteral("flat-base-technic-axle-axis-perpendicular-v1");r.regenerationPrototype=prototype;if(r.artifactIdentity.isEmpty()||d.candidateCount<3||d.candidateCount>9||d.candidateCount%2==0||d.candidateSpacingMillimetres<=0){r.diagnostic=QStringLiteral("The Technic axle artifact definition is invalid.");return r;}const double spacing=16.0;McutMeshBooleanService boolean;r.mesh=box(0,spacing*d.candidateCount,0,16,0,3);auto marked=boolean.unite(r.mesh,box(0,4,15,20,0,2.5));if(!marked.ok()){r.diagnostic=QStringLiteral("Candidate #1 marker could not be joined.");return r;}r.mesh=std::move(marked.mesh);for(int i=0;i<d.candidateCount;++i){const double correction=d.centerTipToTipCorrectionMillimetres+(i-d.candidateCount/2)*d.candidateSpacingMillimetres;auto feature=prototype;feature.stableIdentity=QStringLiteral("%1:candidate-%2").arg(r.artifactIdentity).arg(i+1);feature.frame.origin={8.0+spacing*i,8,2.95};const auto axle=FunctionalOperandRegenerator::regenerateTechnicAxleProfile(feature,{correction});if(!axle.ok()){r.diagnostic=axle.diagnostic;return r;}auto joined=boolean.unite(r.mesh,axle.mesh);if(!joined.ok()){r.diagnostic=QStringLiteral("Technic axle candidate %1 could not be joined.").arg(i+1);return r;}r.mesh=std::move(joined.mesh);FitCalibrationCandidate candidate;candidate.index=i+1;candidate.diameterCorrectionMillimetres=correction;candidate.functionalDiameterMillimetres=4.8+correction;r.candidates.push_back(candidate);}r.analysis=analyzeSource(r.mesh);const auto valid=validatePreparedMesh(r.analysis);if(!valid.ok()){r.diagnostic=QStringLiteral("Technic axle artifact failed validation: %1").arg(QString::fromStdString(valid.message));return r;}r.ok=true;r.diagnostic=QStringLiteral("%1 ordinary Technic axle tip-to-tip candidates generated with protected cross-arm geometry and a Candidate #1-side marker.").arg(d.candidateCount);return r;}
FitCalibrationExperiment TechnicAxleCalibrationArtifact::observationTemplate(const TechnicAxleCalibrationResult&r,const TechnicAxleCalibrationArtifactDefinition&definition){FitCalibrationExperiment e;e.artifactIdentity=r.artifactIdentity;e.parentArtifactIdentity=r.parentArtifactIdentity;e.featureFamily=QStringLiteral("TechnicAxle");e.featureRole=QStringLiteral("male");e.modeledOrientationIdentity=r.orientationIdentity;e.centerDiameterCorrectionMillimetres=definition.centerTipToTipCorrectionMillimetres;e.candidateSpacingMillimetres=definition.candidateSpacingMillimetres;e.regenerationPrototype=r.regenerationPrototype;e.hasRegenerationPrototype=true;e.candidates=r.candidates;e.process.actualPrintedOrientation=FitPrintedOrientation::FeatureAxisPerpendicularToBuildPlate;e.process.orientationNotes=QStringLiteral("Print the flat base on the build plate with axle axes perpendicular. Candidate #1 is beside the raised side marker. Test with ordinary genuine LEGO axle holes, excluding reduced, rounded, and sliding variants.");e.process.dimensionalCompensationNotes=QStringLiteral("Print at 100% scale and record slicer dimensional compensation settings.");return e;}

} // namespace PrintGeometry
