#include "BuildAllocationMutationService.h"
#include "../../database/DatabaseManager.h"
#include "../../repositories/BuildAllocationRepository.h"
#include "../../repositories/BuildRepository.h"
#include "../../repositories/BuildRequirementRepository.h"
#include "../../repositories/InventoryRecordRepository.h"
#include <algorithm>
#include <QHash>

namespace { BuildAllocationMutationService::Result fail(BuildAllocationMutationService::Error e,const QString&m){BuildAllocationMutationService::Result r;r.error=e;r.message=m;return r;} }
BuildAllocationMutationService::BuildAllocationMutationService():BuildAllocationMutationService(DatabaseManager::instance().database()){}
BuildAllocationMutationService::BuildAllocationMutationService(const QSqlDatabase&db):m_connectionName(db.connectionName()){}
QSqlDatabase BuildAllocationMutationService::database()const{return QSqlDatabase::database(m_connectionName,false);}
BuildAllocationMutationService::Result BuildAllocationMutationService::inTransaction(const std::function<Result()>&op)const{auto db=database();if(!db.transaction())return fail(Error::DatabaseFailure,"Unable to begin the allocation transaction.");auto r=op();if(!r.success){db.rollback();return r;}if(!db.commit()){db.rollback();return fail(Error::DatabaseFailure,"Unable to commit the allocation transaction.");}return r;}
BuildAllocationMutationService::Result BuildAllocationMutationService::replaceForRequirement(int id,const QList<BuildAllocation>&a)const{return inTransaction([&]{return replaceForRequirementInCurrentTransaction(id,a);});}
BuildAllocationMutationService::Result BuildAllocationMutationService::replaceForRequirementInCurrentTransaction(int id,const QList<BuildAllocation>&requested)const{
    auto db=database();auto requirement=BuildRequirementRepository(db).getById(id);if(!requirement)return fail(Error::NotFound,"The Build requirement was not found.");
    if(requirement->quantityPulled()>0)return fail(Error::InvalidState,"Allocations cannot change after pieces have been pulled.");
    auto build=BuildRepository(db).getById(requirement->buildId());if(!build)return fail(Error::NotFound,"The Build was not found.");
    BuildAllocationRepository allocations(db);InventoryRecordRepository inventory(db);int total=0;QHash<int,int> requestedByInventory;
    for(const auto& candidate:requested){if(candidate.quantityAllocated()<=0||candidate.inventoryRecordId()<=0)return fail(Error::InvalidInput,"Allocation quantities and Inventory identities must be valid.");auto record=inventory.getById(candidate.inventoryRecordId());if(!record)return fail(Error::NotFound,"An Inventory record was not found.");if(record->workspaceId()!=build->workspaceId()||record->partId()!=requirement->effectivePartId()||record->colorId()!=requirement->effectiveColorId())return fail(Error::InvalidState,"Inventory does not match the requirement's effective Part and Color.");requestedByInventory[candidate.inventoryRecordId()]+=candidate.quantityAllocated();total+=candidate.quantityAllocated();}
    for(auto it=requestedByInventory.cbegin();it!=requestedByInventory.cend();++it){auto record=inventory.getById(it.key());const int existingForRequirement=[&]{int n=0;for(const auto&a:allocations.getByInventoryRecord(it.key()))if(a.buildRequirementId()==id)n+=a.quantityAllocated();return n;}();const int other=qMax(allocations.totalAllocatedForInventoryRecord(it.key())-existingForRequirement,0);if(it.value()>record->quantity()-other)return fail(Error::InvalidState,"The requested allocation exceeds available Inventory.");}
    if(total>qMax(requirement->quantityRequired()-requirement->quantityPulled(),0))return fail(Error::InvalidState,"The requested allocations exceed the remaining requirement quantity.");
    if(!allocations.removeAllForRequirement(id))return fail(Error::DatabaseFailure,"Unable to replace the requirement allocations.");Result out;out.affectedRequirementIds.append(id);
    for(auto candidate:requested){candidate.setBuildId(requirement->buildId());candidate.setBuildRequirementId(id);candidate.setPartId(requirement->effectivePartId());candidate.setColorId(requirement->effectiveColorId());auto record=inventory.getById(candidate.inventoryRecordId());candidate.setStorageLocationId(record->storageLocationId());if(!allocations.create(candidate))return fail(Error::DatabaseFailure,"Unable to create a requirement allocation.");out.allocations.append(candidate);out.affectedInventoryIds.append(candidate.inventoryRecordId());}
    out.success=true;out.changed=true;out.message="Allocations replaced.";return out;
}
BuildAllocationMutationService::Result BuildAllocationMutationService::allocateAvailable(int id,int preferred)const{return inTransaction([&]{return allocateAvailableInCurrentTransaction(id,preferred);});}
BuildAllocationMutationService::Result BuildAllocationMutationService::allocateAvailableInCurrentTransaction(int buildId,int preferred)const{
    auto db=database();auto build=BuildRepository(db).getById(buildId);if(!build)return fail(Error::NotFound,"The Build was not found.");if(build->inventoryMode()!=QStringLiteral("Stock"))return fail(Error::InvalidState,"Automatic allocation is available only for Build from Stock.");BuildRequirementRepository requirements(db);BuildAllocationRepository allocations(db);InventoryRecordRepository inventory(db);Result out;
    for(const auto&r:requirements.getByBuild(buildId)){if(r.isSpare())continue;int needed=qMax(r.quantityRequired()-r.quantityPulled()-allocations.totalAllocatedForRequirement(r.id()),0);if(!needed)continue;auto records=inventory.getByPartColor(build->workspaceId(),r.effectivePartId(),r.effectiveColorId());std::stable_sort(records.begin(),records.end(),[preferred](const auto&a,const auto&b){return a.storageLocationId()==preferred&&b.storageLocationId()!=preferred;});for(const auto&record:records){if(!needed)break;const int available=qMax(record.quantity()-allocations.totalAllocatedForInventoryRecord(record.id()),0);const int add=qMin(needed,available);if(!add)continue;auto current=allocations.getByRequirement(r.id());auto it=std::find_if(current.begin(),current.end(),[&](const auto&a){return a.inventoryRecordId()==record.id();});if(it!=current.end()){it->setQuantityAllocated(it->quantityAllocated()+add);if(!allocations.update(*it))return fail(Error::DatabaseFailure,"Unable to update an allocation.");++out.allocationsUpdated;}else{BuildAllocation a;a.setBuildId(buildId);a.setBuildRequirementId(r.id());a.setInventoryRecordId(record.id());a.setPartId(r.effectivePartId());a.setColorId(r.effectiveColorId());a.setStorageLocationId(record.storageLocationId());a.setQuantityAllocated(add);if(!allocations.create(a))return fail(Error::DatabaseFailure,"Unable to create an allocation.");++out.allocationsCreated;}needed-=add;out.piecesAdded+=add;if(preferred>0&&record.storageLocationId()==preferred)out.preferredPiecesAdded+=add;out.affectedInventoryIds.append(record.id());if(!out.affectedRequirementIds.contains(r.id()))out.affectedRequirementIds.append(r.id());}}
    out.allocations=allocations.getByBuild(buildId);out.success=true;out.changed=out.piecesAdded>0;out.message=out.changed?"Available Inventory allocated.":"No additional Inventory was available.";return out;
}
