#include "BuildRequirementMutationService.h"
#include "../../database/DatabaseManager.h"
#include "../../repositories/BuildAllocationRepository.h"
#include "../../repositories/BuildRepository.h"
#include "../../repositories/BuildRequirementRepository.h"
#include "../../repositories/ColorRepository.h"
#include "../../repositories/PartRepository.h"
#include <QSqlError>

namespace { BuildRequirementMutationService::Result fail(BuildRequirementMutationService::Error e,const QString&m){BuildRequirementMutationService::Result r;r.error=e;r.message=m;return r;} }
BuildRequirementMutationService::BuildRequirementMutationService():BuildRequirementMutationService(DatabaseManager::instance().database()){}
BuildRequirementMutationService::BuildRequirementMutationService(const QSqlDatabase&db):m_connectionName(db.connectionName()){}
QSqlDatabase BuildRequirementMutationService::database()const{return QSqlDatabase::database(m_connectionName,false);}
BuildRequirementMutationService::Result BuildRequirementMutationService::inTransaction(const std::function<Result()>&op)const{auto db=database();if(!db.transaction())return fail(Error::DatabaseFailure,"Unable to begin the requirement transaction.");auto r=op();if(!r.success){db.rollback();return r;}if(!db.commit()){db.rollback();return fail(Error::DatabaseFailure,"Unable to commit the requirement transaction.");}return r;}
BuildRequirementMutationService::Result BuildRequirementMutationService::add(BuildRequirement r)const{return inTransaction([&]{return addInCurrentTransaction(r);});}
BuildRequirementMutationService::Result BuildRequirementMutationService::addInCurrentTransaction(BuildRequirement r)const{auto db=database();if(r.buildId()<=0||r.partId()<=0||r.colorId()<=0||r.quantityRequired()<=0)return fail(Error::InvalidInput,"Enter valid requirement details.");auto b=BuildRepository(db).getById(r.buildId());if(!b)return fail(Error::NotFound,"The Build was not found.");if(b->inventoryMode()!=QStringLiteral("Stock"))return fail(Error::InvalidState,"Manual requirements are available only for Build from Stock.");if(!PartRepository(db).getById(r.partId())||!ColorRepository(db).getById(r.colorId()))return fail(Error::NotFound,"The Part or Color was not found.");if(!BuildRequirementRepository(db).create(r))return fail(Error::DatabaseFailure,"Unable to add the Build requirement.");Result out;out.success=out.changed=true;out.requirement=r;out.message="Requirement added.";return out;}
BuildRequirementMutationService::Result BuildRequirementMutationService::edit(int id,int p,int c,int q,bool s)const{return inTransaction([&]{return editInCurrentTransaction(id,p,c,q,s);});}
BuildRequirementMutationService::Result BuildRequirementMutationService::editInCurrentTransaction(int id,int p,int c,int q,bool s)const{auto db=database();std::optional<BuildRequirement> r;if(!BuildRequirementRepository(db).tryGetById(id,r))return fail(Error::DatabaseFailure,"Unable to read the requirement.");if(!r)return fail(Error::NotFound,"The requirement was not found.");std::optional<Build>b;if(!BuildRepository(db).tryGetById(r->buildId(),b))return fail(Error::DatabaseFailure,"Unable to read the Build.");if(!b)return fail(Error::NotFound,"The Build was not found.");if(b->inventoryMode()!=QStringLiteral("Stock"))return fail(Error::InvalidState,"Requirement substitutions are available only for Build from Stock.");if(q<=0)return fail(Error::InvalidInput,"Quantity must be positive.");if((p>0&&!PartRepository(db).getById(p))||(c>0&&!ColorRepository(db).getById(c)))return fail(Error::NotFound,"The substitute Part or Color was not found.");const bool identityChanged=p!=r->substitutePartId()||c!=r->substituteColorId();if(identityChanged){auto allocations=BuildAllocationRepository(db);if(allocations.totalAllocatedForRequirement(id)>0||allocations.totalAllocatedForPartColorForBuild(r->buildId(),r->effectivePartId(),r->effectiveColorId())>0)return fail(Error::InvalidState,"Part or Color cannot change while inventory is allocated.");}const bool changed=identityChanged||q!=r->quantityRequired()||s!=r->isSpare();r->setSubstitutePartId(p);r->setSubstituteColorId(c);r->setQuantityRequired(q);r->setIsSpare(s);if(changed&&!BuildRequirementRepository(db).update(*r))return fail(Error::DatabaseFailure,"Unable to update the requirement.");Result out;out.success=true;out.changed=changed;out.requirement=*r;out.message=changed?"Requirement updated.":"No changes.";return out;}
BuildRequirementMutationService::Result BuildRequirementMutationService::remove(int id)const{return inTransaction([&]{return removeInCurrentTransaction(id);});}
BuildRequirementMutationService::Result BuildRequirementMutationService::removeInCurrentTransaction(int id)const{auto db=database();std::optional<BuildRequirement> r;if(!BuildRequirementRepository(db).tryGetById(id,r))return fail(Error::DatabaseFailure,"Unable to read the requirement.");if(!r)return fail(Error::NotFound,"The requirement was not found.");auto a=BuildAllocationRepository(db);if(r->quantityPulled()>0||r->quantityReleased()>0||a.totalAllocatedForRequirement(id)>0)return fail(Error::InvalidState,"A requirement with pulled, released, or allocated pieces cannot be removed.");if(!BuildRequirementRepository(db).remove(id))return fail(Error::DatabaseFailure,"Unable to remove the requirement.");Result out;out.success=out.changed=true;out.requirement=*r;out.message="Requirement removed.";return out;}
