#include "RemoteBuildabilityDtos.h"

#include <QJsonArray>
#include <climits>

namespace {
bool fail(QString* error, const QString& message) { if (error) *error = message; return false; }
bool exact(const QJsonObject& o, int count) { return o.size() == count; }
bool text(const QJsonObject& o, const char* key, QString* out, bool empty, int maximum)
{ const auto v=o.value(QLatin1String(key)); if(!v.isString())return false;*out=v.toString();return out->size()<=maximum&&(empty||!out->trimmed().isEmpty()); }
bool integer(const QJsonObject& o,const char* key,qint64 minimum,qint64 maximum,qint64* out)
{ const auto v=o.value(QLatin1String(key));if(!v.isDouble())return false;const double d=v.toDouble();const qint64 n=qint64(d);if(double(n)!=d||n<minimum||n>maximum)return false;*out=n;return true; }
bool boolean(const QJsonObject&o,const char*key,bool*out){const auto v=o.value(QLatin1String(key));if(!v.isBool())return false;*out=v.toBool();return true;}
}

namespace RemoteBuildabilityDto {
QJsonObject toJson(const SearchRequest&v){return{{"workspaceId",double(v.workspaceId)},{"text",v.text},{"minimumPercent",v.minimumPercent},{"minimumSetParts",v.minimumSetParts},{"yearFrom",v.yearFrom},{"yearTo",v.yearTo},{"rebrickableThemeId",v.rebrickableThemeId},{"fullyBuildableOnly",v.fullyBuildableOnly},{"includeCollection",v.includeCollection},{"fullyBuildableFirst",v.fullyBuildableFirst},{"maximumResults",v.maximumResults}};}
bool fromJson(const QJsonObject&o,SearchRequest*v,QString*e){if(!v||!exact(o,11))return fail(e,"Invalid buildability search request.");SearchRequest x;qint64 w,p,s,yf,yt,t,m;if(!integer(o,"workspaceId",1,9007199254740991LL,&w)||!text(o,"text",&x.text,true,RemoteReadDto::MaximumTextLength)||!integer(o,"minimumPercent",0,100,&p)||!integer(o,"minimumSetParts",1,10000,&s)||!integer(o,"yearFrom",0,9999,&yf)||!integer(o,"yearTo",0,9999,&yt)||!integer(o,"rebrickableThemeId",0,INT_MAX,&t)||!boolean(o,"fullyBuildableOnly",&x.fullyBuildableOnly)||!boolean(o,"includeCollection",&x.includeCollection)||!boolean(o,"fullyBuildableFirst",&x.fullyBuildableFirst)||!integer(o,"maximumResults",1,MaximumResults,&m)||(yf&&yt&&yf>yt))return fail(e,"Invalid buildability search request.");x.workspaceId=w;x.minimumPercent=p;x.minimumSetParts=s;x.yearFrom=yf;x.yearTo=yt;x.rebrickableThemeId=t;x.maximumResults=m;*v=x;return true;}
QJsonObject toJson(const CompactResult&v){return{{"setNumber",v.setNumber},{"name",v.name},{"year",v.year},{"rebrickableThemeId",v.rebrickableThemeId},{"qualifiedThemeName",v.qualifiedThemeName},{"imageUrl",v.imageUrl},{"catalogPartCount",v.catalogPartCount},{"totalRequiredPieces",v.totalRequiredPieces},{"totalRequirements",v.totalRequirements},{"looseSatisfiedPieces",v.looseSatisfiedPieces},{"looseSatisfiedRequirements",v.looseSatisfiedRequirements},{"advisorySatisfiedPieces",v.advisorySatisfiedPieces},{"advisorySatisfiedRequirements",v.advisorySatisfiedRequirements},{"missingPieces",v.missingPieces},{"usesCollection",v.usesCollection},{"collectionSourceCount",v.collectionSourceCount}};}
bool fromJson(const QJsonObject&o,CompactResult*v,QString*e){if(!v||!exact(o,16))return fail(e,"Invalid buildability result.");CompactResult x;qint64 year,theme,catalog,total,req,lp,lr,ap,ar,missing,sources;if(!text(o,"setNumber",&x.setNumber,false,128)||!text(o,"name",&x.name,true,1024)||!integer(o,"year",0,9999,&year)||!integer(o,"rebrickableThemeId",0,INT_MAX,&theme)||!text(o,"qualifiedThemeName",&x.qualifiedThemeName,true,1024)||!text(o,"imageUrl",&x.imageUrl,true,4096)||!integer(o,"catalogPartCount",0,INT_MAX,&catalog)||!integer(o,"totalRequiredPieces",1,INT_MAX,&total)||!integer(o,"totalRequirements",1,INT_MAX,&req)||!integer(o,"looseSatisfiedPieces",0,total,&lp)||!integer(o,"looseSatisfiedRequirements",0,req,&lr)||!integer(o,"advisorySatisfiedPieces",0,total,&ap)||!integer(o,"advisorySatisfiedRequirements",0,req,&ar)||!integer(o,"missingPieces",0,total,&missing)||!boolean(o,"usesCollection",&x.usesCollection)||!integer(o,"collectionSourceCount",0,MaximumCollectionSources,&sources)||missing!=total-ap||ap<lp||ar<lr||x.usesCollection!=(sources>0))return fail(e,"Invalid buildability result.");x.year=year;x.rebrickableThemeId=theme;x.catalogPartCount=catalog;x.totalRequiredPieces=total;x.totalRequirements=req;x.looseSatisfiedPieces=lp;x.looseSatisfiedRequirements=lr;x.advisorySatisfiedPieces=ap;x.advisorySatisfiedRequirements=ar;x.missingPieces=missing;x.collectionSourceCount=sources;*v=x;return true;}
QJsonObject toJson(const SearchResponse&v){QJsonArray a;for(const auto&x:v.rows)a.append(toJson(x));return{{"rows",a},{"qualifyingCount",v.qualifyingCount},{"returnedCount",v.returnedCount},{"capReached",v.capReached},{"eligibleCollectionSourceCount",v.eligibleCollectionSourceCount},{"dormantCollectionSourceCount",v.dormantCollectionSourceCount}};}
bool fromJson(const QJsonObject&o,SearchResponse*v,QString*e){if(!v||!exact(o,6)||!o.value("rows").isArray()||!o.value("capReached").isBool())return fail(e,"Invalid buildability search response.");SearchResponse x;qint64 q,r,eligible,dormant;if(!integer(o,"qualifyingCount",0,INT_MAX,&q)||!integer(o,"returnedCount",0,MaximumResults,&r)||!integer(o,"eligibleCollectionSourceCount",0,INT_MAX,&eligible)||!integer(o,"dormantCollectionSourceCount",0,INT_MAX,&dormant))return fail(e,"Invalid buildability search response.");const auto a=o.value("rows").toArray();const bool capped=o.value("capReached").toBool();if(a.size()!=r||q<r||capped!=(q>r))return fail(e,"Invalid buildability search response.");for(const auto&j:a){CompactResult row;if(!j.isObject()||!fromJson(j.toObject(),&row,e))return false;x.rows.append(row);}x.qualifyingCount=q;x.returnedCount=r;x.capReached=capped;x.eligibleCollectionSourceCount=eligible;x.dormantCollectionSourceCount=dormant;*v=x;return true;}
QJsonObject toJson(const DetailsRequest&v){return{{"workspaceId",double(v.workspaceId)},{"setNumber",v.setNumber},{"includeCollection",v.includeCollection},{"page",v.paging.page},{"pageSize",v.paging.pageSize}};}
bool fromJson(const QJsonObject&o,DetailsRequest*v,QString*e){if(!v||!exact(o,5))return fail(e,"Invalid buildability details request.");DetailsRequest x;qint64 w,p,s;if(!integer(o,"workspaceId",1,9007199254740991LL,&w)||!text(o,"setNumber",&x.setNumber,false,128)||!boolean(o,"includeCollection",&x.includeCollection)||!integer(o,"page",1,INT_MAX,&p)||!integer(o,"pageSize",1,MaximumRequirementPageSize,&s))return fail(e,"Invalid buildability details request.");x.workspaceId=w;x.paging.page=p;x.paging.pageSize=s;*v=x;return true;}
QJsonObject toJson(const Requirement&v){return{{"partNumber",v.partNumber},{"partDescription",v.partDescription},{"rebrickableColorId",v.rebrickableColorId},{"colorName",v.colorName},{"requiredQuantity",v.requiredQuantity},{"looseAvailableQuantity",v.looseAvailableQuantity},{"looseUsedQuantity",v.looseUsedQuantity},{"collectionUsedQuantity",v.collectionUsedQuantity},{"missingQuantity",v.missingQuantity}};}
bool fromJson(const QJsonObject&o,Requirement*v,QString*e){if(!v||!exact(o,9))return fail(e,"Invalid buildability requirement.");Requirement x;qint64 color,required,available,loose,collection,missing;if(!text(o,"partNumber",&x.partNumber,false,128)||!text(o,"partDescription",&x.partDescription,true,1024)||!integer(o,"rebrickableColorId",-1,INT_MAX,&color)||!text(o,"colorName",&x.colorName,true,512)||!integer(o,"requiredQuantity",1,INT_MAX,&required)||!integer(o,"looseAvailableQuantity",0,INT_MAX,&available)||!integer(o,"looseUsedQuantity",0,required,&loose)||!integer(o,"collectionUsedQuantity",0,required-loose,&collection)||!integer(o,"missingQuantity",0,required,&missing)||loose+collection+missing!=required)return fail(e,"Invalid buildability requirement.");x.rebrickableColorId=color;x.requiredQuantity=required;x.looseAvailableQuantity=available;x.looseUsedQuantity=loose;x.collectionUsedQuantity=collection;x.missingQuantity=missing;*v=x;return true;}
QJsonObject toJson(const CollectionSource&v){return{{"collectionItemId",double(v.collectionItemId)},{"displayLabel",v.displayLabel},{"state",v.state},{"piecesUsed",v.piecesUsed}};}
bool fromJson(const QJsonObject&o,CollectionSource*v,QString*e){if(!v||!exact(o,4))return fail(e,"Invalid buildability Collection source.");CollectionSource x;qint64 id,pieces;if(!integer(o,"collectionItemId",1,9007199254740991LL,&id)||!text(o,"displayLabel",&x.displayLabel,false,1024)||!text(o,"state",&x.state,false,128)||!integer(o,"piecesUsed",1,INT_MAX,&pieces))return fail(e,"Invalid buildability Collection source.");x.collectionItemId=id;x.piecesUsed=pieces;*v=x;return true;}
QJsonObject toJson(const DetailsResponse&v){QJsonArray requirements,sources;for(const auto&x:v.requirements)requirements.append(toJson(x));for(const auto&x:v.sources)sources.append(toJson(x));return{{"candidate",toJson(v.candidate)},{"requirements",requirements},{"sources",sources},{"page",v.page},{"pageSize",v.pageSize},{"totalCount",v.totalCount},{"returnedCount",v.returnedCount}};}
bool fromJson(const QJsonObject&o,DetailsResponse*v,QString*e){if(!v||!exact(o,7)||!o.value("candidate").isObject()||!o.value("requirements").isArray()||!o.value("sources").isArray())return fail(e,"Invalid buildability details response.");DetailsResponse x;qint64 page,size,total,returned;if(!fromJson(o.value("candidate").toObject(),&x.candidate,e)||!integer(o,"page",1,INT_MAX,&page)||!integer(o,"pageSize",1,MaximumRequirementPageSize,&size)||!integer(o,"totalCount",0,INT_MAX,&total)||!integer(o,"returnedCount",0,size,&returned))return fail(e,"Invalid buildability details response.");const auto ra=o.value("requirements").toArray(),sa=o.value("sources").toArray();const qint64 offset=(page-1)*size;const qint64 expected=offset>=total?0:qMin(size,total-offset);if(ra.size()!=returned||returned!=expected||sa.size()>MaximumCollectionSources)return fail(e,"Invalid buildability details response.");for(const auto&j:ra){Requirement row;if(!j.isObject()||!fromJson(j.toObject(),&row,e))return false;x.requirements.append(row);}for(const auto&j:sa){CollectionSource row;if(!j.isObject()||!fromJson(j.toObject(),&row,e))return false;x.sources.append(row);}x.page=page;x.pageSize=size;x.totalCount=total;x.returnedCount=returned;*v=x;return true;}
} // namespace RemoteBuildabilityDto
