#include "HostCollectionMutationService.h"
#include "dto/RemoteCollectionMutationDtos.h"
#include "../collection/CollectionItemService.h"
#include "../../repositories/CollectionRepository.h"
#include "../../repositories/SetCatalogRepository.h"
#include "../../repositories/MinifigCatalogRepository.h"
#include "../../repositories/StorageLocationRepository.h"

namespace {
HostWriteExecutor::MutationOutcome fail(const QString&c,const QString&m,bool refresh=false){HostWriteExecutor::MutationOutcome o;o.error={c,m,false};if(refresh)o.error.conflict={{"refreshRequired",true}};return o;}
QString minifigNumber(const QSqlDatabase&db,int id){for(const auto&x:MinifigCatalogRepository(db).identifiersForMinifig(id))if(x.provider.compare("Rebrickable",Qt::CaseInsensitive)==0)return x.externalId;return{};}
QString setNumber(const QSqlDatabase&db,int id){auto x=SetCatalogRepository(db).getById(id);return x?x->setNumber():QString();}
QJsonObject detail(const QSqlDatabase&db,const CollectionItem&i){QString set,fig,path;if(i.setCatalogId>0){auto x=SetCatalogRepository(db).getById(i.setCatalogId);if(x)set=x->setNumber();}if(i.minifigCatalogId>0)fig=minifigNumber(db,i.minifigCatalogId);if(i.storageLocationId>0){auto x=StorageLocationRepository(db).getById(i.storageLocationId);if(x)path=x->name();}return{{"collectionItemId",i.id},{"workspaceId",i.workspaceId},{"type",collectionItemTypeToString(i.type)},{"setNumber",set},{"minifigNumber",fig},{"sourceBuildId",i.sourceBuildId},{"state",collectionItemStateToString(i.state)},{"condition",collectionItemConditionToString(i.condition)},{"completeness",collectionItemCompletenessToString(i.completeness)},{"storageId",i.storageLocationId},{"storagePath",path},{"nickname",i.nickname},{"notes",i.notes},{"active",i.isActive},{"createdUtc",i.createdUtc.toUTC().toString(Qt::ISODateWithMs)},{"modifiedUtc",i.modifiedUtc.toUTC().toString(Qt::ISODateWithMs)}};}
bool matches(const QSqlDatabase&db,const CollectionItem&i,const RemoteCollectionMutationDto::ExpectedState&e){return i.modifiedUtc.toUTC().toString(Qt::ISODateWithMs)==e.modifiedUtc&&i.isActive==e.active&&collectionItemTypeToString(i.type)==e.type&&setNumber(db,i.setCatalogId)==e.setNumber&&minifigNumber(db,i.minifigCatalogId)==e.minifigNumber&&i.sourceBuildId==e.sourceBuildId&&collectionItemStateToString(i.state)==e.state&&collectionItemConditionToString(i.condition)==e.condition&&collectionItemCompletenessToString(i.completeness)==e.completeness&&i.storageLocationId==e.storageId&&i.nickname==e.nickname&&i.notes==e.notes;}
HostWriteExecutor::MutationOutcome map(const QSqlDatabase&db,const CollectionItemService::Result&r){if(!r.success){QString code="INVALID_ARGUMENT";if(r.error==CollectionItemService::Error::ItemNotFound||r.error==CollectionItemService::Error::CatalogItemNotFound||r.error==CollectionItemService::Error::SourceBuildNotFound)code="NOT_FOUND";else if(r.error==CollectionItemService::Error::SourceBuildAlreadyUsed)code="CONFLICT";else if(r.error==CollectionItemService::Error::DatabaseFailure)code="INTERNAL_ERROR";return fail(code,r.message,code=="CONFLICT");}HostWriteExecutor::MutationOutcome o;o.success=true;o.authoritative={{"item",detail(db,r.item)}};o.publicationWorkflow=HostMutationPublicationService::Workflow::Collection;o.publicationScope.workspaceId=r.item.workspaceId;o.publicationScope.collectionItemId=r.item.id;return o;}
}
HostWriteExecutor::Mutation HostCollectionMutationService::createMutation(const QString&op,const RemoteMutationDto::Metadata&md,RemoteMutationDto::Error*error){RemoteCollectionMutationDto::Request r;if(!RemoteCollectionMutationDto::fromMetadata(op,md,&r,error))return{};return[op,r](const QSqlDatabase&db){CollectionItemService service(db);if(op=="collection.add"){CollectionItemService::Result result;if(r.sourceType=="SetCatalog"){bool ok=false;auto rows=SetCatalogRepository(db).getExactMatchesBySetNumber(r.setNumber,&ok);if(!ok)return fail("INTERNAL_ERROR","The Host could not resolve the Set identity.");if(rows.size()!=1)return fail(rows.isEmpty()?"NOT_FOUND":"CONFLICT","The Rebrickable Set identity is unavailable or ambiguous.");result=service.createSetInCurrentTransaction(r.workspaceId,rows.first().id(),collectionItemStateFromString(r.state),r.storageId,0,r.nickname,r.notes,collectionItemConditionFromString(r.condition),collectionItemCompletenessFromString(r.completeness));}else if(r.sourceType=="MinifigCatalog"){bool ok=false;auto x=MinifigCatalogRepository(db).getByExternalIdentifier("Rebrickable",r.minifigNumber,&ok);if(!ok)return fail("INTERNAL_ERROR","The Host could not resolve the Minifig identity.");if(!x)return fail("NOT_FOUND","The Rebrickable Minifig identity is unavailable.");result=service.createMinifigInCurrentTransaction(r.workspaceId,x->id(),collectionItemStateFromString(r.state),r.storageId,0,r.nickname,r.notes,collectionItemConditionFromString(r.condition),collectionItemCompletenessFromString(r.completeness));}else if(r.sourceType=="Build")result=service.createFromBuildInCurrentTransaction(r.workspaceId,r.buildId,collectionItemStateFromString(r.state),r.storageId,r.nickname,r.notes,collectionItemConditionFromString(r.condition),collectionItemCompletenessFromString(r.completeness));else return fail("INVALID_ARGUMENT","The Collection source type is unsupported.");return map(db,result);}std::optional<CollectionItem> item;if(!CollectionRepository(db).tryGetById(r.collectionItemId,item))return fail("INTERNAL_ERROR","The Host could not read the Collection item.");if(!item||item->workspaceId!=r.workspaceId)return fail("NOT_FOUND","The Collection item was not found in this Workspace.");if(!matches(db,*item,r.expected))return fail("STALE_VERSION","The Collection item changed. Refresh and try again.",true);if(op=="collection.edit")return map(db,service.updateDetailsInCurrentTransaction(item->id,collectionItemStateFromString(r.state),r.storageId,r.nickname,r.notes,item->allowPartsSource,collectionItemConditionFromString(r.condition),collectionItemCompletenessFromString(r.completeness)));return map(db,service.setActiveInCurrentTransaction(item->id,r.desiredActive));};}
