#include "HostReadProtocolService.h"
#include "HostReadExecutor.h"
#include "dto/RemoteReadJson.h"
#include "../../network/BrickSuiteOperationDispatcher.h"
#include "../parts/PartReferenceManifest.h"
#include <QHash>
#include <QJsonArray>
#include <QSet>
namespace {
using Completion=BrickSuiteOperationDispatcher::Completion;
bool positiveId(const QJsonObject&o,const char*name,int*out){const auto v=o.value(QLatin1String(name));if(!v.isDouble())return false;double d=v.toDouble();int n=v.toInt();if(d!=double(n)||n<=0)return false;*out=n;return true;}
void invalid(const BrickSuiteProtocol::Message&r,Completion c,const QString&m){c(BrickSuiteProtocol::errorResponse(r,"INVALID_REQUEST",m));}
void failed(const BrickSuiteProtocol::Message&r,Completion c,const QString&){c(BrickSuiteProtocol::errorResponse(r,"SERVER_BUSY","The Host read service is temporarily unavailable.",true));}
}
HostReadProtocolService::HostReadProtocolService(const QString&p,QObject*parent):QObject(parent),m_executor(std::make_unique<HostReadExecutor>(p,this)){}
HostReadProtocolService::~HostReadProtocolService()=default;
bool HostReadProtocolService::isAvailable()const{return m_executor&&m_executor->isAccepting();}
void HostReadProtocolService::registerOperations(BrickSuiteOperationDispatcher& d)
{
 d.registerAsyncOperation("workspace.list",true,[this](const auto&r,Completion c){if(!r.payload.isEmpty()){invalid(r,std::move(c),"workspace.list does not accept payload fields.");return;}m_executor->listWorkspaces(this,[r,c](const QList<Workspace>&rows){QJsonArray a;for(const auto&w:rows){RemoteReadDto::WorkspaceSummary v{w.id(),w.name()};a.append(RemoteReadJson::toJson(v));}c(BrickSuiteProtocol::response(r,{{"rows",a}}));},[r,c](const QString&e){failed(r,c,e);});});
 d.registerAsyncOperation("storage.list",true,[this](const auto&r,Completion c){int wid=0;if(r.payload.size()!=1||!positiveId(r.payload,"workspaceId",&wid)){invalid(r,std::move(c),"A positive workspaceId is required.");return;}m_executor->listStorage(wid,this,[r,c](const QList<StorageLocation>&rows){QHash<int,StorageLocation> map;for(const auto&x:rows)map.insert(x.id(),x);QJsonArray a;for(const auto&x:rows){QStringList names;QSet<int>seen;int id=x.id();while(id>0&&map.contains(id)&&!seen.contains(id)){seen.insert(id);names.prepend(map[id].name());id=map[id].parentLocationId();}RemoteReadDto::StorageSummary v{x.id(),x.parentLocationId(),x.name(),names.join(" / "),x.isActive()};a.append(RemoteReadJson::toJson(v));}c(BrickSuiteProtocol::response(r,{{"rows",a}}));},[r,c](const QString&e){failed(r,c,e);});});
 d.registerAsyncOperation("inventory.search",true,[this](const auto&r,Completion c){int wid=0;RemoteReadDto::PageRequest p;int color=-1,storage=0;const double cd=r.payload.value("rebrickableColorId").toDouble(-2),sd=r.payload.value("storageId").toDouble(-1);if(r.payload.size()!=6||!positiveId(r.payload,"workspaceId",&wid)||!RemoteReadJson::pageRequest(r.payload,&p)||!r.payload.value("text").isString()||r.payload.value("text").toString().size()>RemoteReadDto::MaximumTextLength||cd!=double(color=r.payload.value("rebrickableColorId").toInt(-2))||color<-1||sd!=double(storage=r.payload.value("storageId").toInt(-1))||storage<0){invalid(r,std::move(c),"The Inventory search criteria are invalid.");return;}RemoteReadDto::InventorySearchRequest q;q.workspaceId=wid;q.text=r.payload.value("text").toString();q.storageId=storage;q.rebrickableColorId=color;q.paging=p;m_executor->searchInventoryPortable(q,this,[r,c,p,wid](const InventoryApplicationService::Page&result){QJsonArray a;for(const auto&x:result.rows){RemoteReadDto::InventoryRow v;v.inventoryRecordId=x.inventoryRecordId;v.workspaceId=wid;v.partNumber=x.partNumber;v.partNameFallback=x.partName;v.rebrickableColorId=x.rebrickableColorId;v.colorNameFallback=x.colorName;v.quantity=x.quantity;v.storageId=x.storageLocationId;v.storagePath=x.storageLocationName;v.manufacturerDisplay=x.manufacturerName;v.condition=x.condition;v.ownershipType=x.ownershipType;a.append(RemoteReadJson::toJson(v));}c(BrickSuiteProtocol::response(r,{{"rows",a},{"page",p.page},{"pageSize",p.pageSize},{"totalRows",result.total}}));},[r,c](const QString&e){failed(r,c,e);});});
 d.registerAsyncOperation("inventory.get",true,[this](const auto&r,Completion c){int id=0;if(r.payload.size()!=1||!positiveId(r.payload,"inventoryRecordId",&id)){invalid(r,std::move(c),"A positive inventoryRecordId is required.");return;}m_executor->getInventoryPortable(id,this,[r,c](const std::optional<RemoteReadDto::InventoryDetail>&x){if(!x){c(BrickSuiteProtocol::errorResponse(r,"NOT_FOUND","The requested Inventory record was not found."));return;}c(BrickSuiteProtocol::response(r,{{"item",RemoteReadJson::toJson(*x)}}));},[r,c](const QString&e){failed(r,c,e);});});
 d.registerAsyncOperation("inventory.history",true,[this](const auto&r,Completion c){int wid=0;int color=-1;const auto cv=r.payload.value("rebrickableColorId");const auto pv=r.payload.value("partNumber");const double cd=cv.toDouble(-1);if(r.payload.size()!=3||!positiveId(r.payload,"workspaceId",&wid)||!cv.isDouble()||cd!=double(color=cv.toInt(-1))||color<0||!pv.isString()||pv.toString().trimmed().isEmpty()||pv.toString().size()>RemoteReadDto::MaximumTextLength){invalid(r,std::move(c),"Canonical Part and Color identities and a positive workspaceId are required.");return;}m_executor->inventoryHistoryPortable(wid,pv.toString(),color,this,[r,c](const QList<RemoteReadDto::InventoryHistoryRow>&rows){QJsonArray a;for(const auto&x:rows)a.append(RemoteReadJson::toJson(x));c(BrickSuiteProtocol::response(r,{{"rows",a}}));},[r,c](const QString&e){failed(r,c,e);});});
 d.registerAsyncOperation("builds.list",true,[this](const auto&r,Completion c){int wid=0;if(!positiveId(r.payload,"workspaceId",&wid)||!r.payload.value("includeArchived").isBool()){invalid(r,std::move(c),"The Build list criteria are invalid.");return;}m_executor->listBuilds(wid,r.payload.value("includeArchived").toBool(),this,[r,c](const QList<Build>&rows){QJsonArray a;for(const auto&x:rows){RemoteReadDto::BuildSummary v;v.buildId=x.id();v.workspaceId=x.workspaceId();v.buildType=x.buildType();v.name=x.name();v.setNumber=x.setNumber();if(x.buildType()=="Minifig")v.minifigNumber=x.sourceReference();v.inventoryMode=x.inventoryMode();v.status=x.status();v.active=x.isActive();a.append(RemoteReadJson::toJson(v));}c(BrickSuiteProtocol::response(r,{{"rows",a}}));},[r,c](const QString&e){failed(r,c,e);});});
 d.registerAsyncOperation("builds.get",true,[this](const auto&r,Completion c){int id=0;if(r.payload.size()!=1||!positiveId(r.payload,"buildId",&id)){invalid(r,std::move(c),"A positive buildId is required.");return;}m_executor->getBuild(id,this,[r,c](const std::optional<Build>&x){if(!x){c(BrickSuiteProtocol::errorResponse(r,"NOT_FOUND","The requested Build was not found."));return;}RemoteReadDto::BuildSummary v;v.buildId=x->id();v.workspaceId=x->workspaceId();v.buildType=x->buildType();v.name=x->name();v.setNumber=x->setNumber();if(x->buildType()=="Minifig")v.minifigNumber=x->sourceReference();v.inventoryMode=x->inventoryMode();v.status=x->status();v.active=x->isActive();c(BrickSuiteProtocol::response(r,{{"build",RemoteReadJson::toJson(v)}}));},[r,c](const QString&e){failed(r,c,e);});});
 const auto pagedBuild=[this,&d](const QString&operation,auto submit){d.registerAsyncOperation(operation,true,[this,submit](const auto&r,Completion c){int id=0;RemoteReadDto::PageRequest p;if(r.payload.size()!=3||!positiveId(r.payload,"buildId",&id)||!RemoteReadJson::pageRequest(r.payload,&p)){invalid(r,std::move(c),"A positive buildId and valid paging are required.");return;}submit(id,p,r,std::move(c));});};
 pagedBuild("builds.requirements",[this](int id,const auto&p,const auto&r,Completion c){m_executor->buildRequirementsPortable(id,p,this,[r,c](const auto&result){QJsonArray a;for(const auto&x:result.rows)a.append(RemoteReadJson::toJson(x));c(BrickSuiteProtocol::response(r,{{"rows",a},{"page",result.page},{"pageSize",result.pageSize},{"totalRows",result.totalRows}}));},[r,c](const QString&e){failed(r,c,e);});});
 d.registerAsyncOperation("builds.missingParts",true,[this](const auto&r,Completion c){int id=0,wid=0;RemoteReadDto::PageRequest p;if(r.payload.size()!=4||!positiveId(r.payload,"buildId",&id)||!positiveId(r.payload,"workspaceId",&wid)||!RemoteReadJson::pageRequest(r.payload,&p)){invalid(r,std::move(c),"Positive Build/Workspace IDs and valid paging are required.");return;}m_executor->missingPartsPortable(wid,id,p,this,[r,c](const auto&result){QJsonArray a;for(const auto&x:result.rows)a.append(RemoteReadJson::toJson(x));c(BrickSuiteProtocol::response(r,{{"rows",a},{"page",result.page},{"pageSize",result.pageSize},{"totalRows",result.totalRows}}));},[r,c](const QString&e){failed(r,c,e);});});
 pagedBuild("builds.pulling",[this](int id,const auto&p,const auto&r,Completion c){m_executor->pullingPortable(id,p,this,[r,c](const auto&result){QJsonArray a;for(const auto&x:result.rows)a.append(RemoteReadJson::toJson(x));c(BrickSuiteProtocol::response(r,{{"rows",a},{"page",result.page},{"pageSize",result.pageSize},{"totalRows",result.totalRows}}));},[r,c](const QString&e){failed(r,c,e);});});
 d.registerAsyncOperation("collection.search",true,[this](const auto&r,Completion c){int wid=0;RemoteReadDto::PageRequest p;if(!positiveId(r.payload,"workspaceId",&wid)||!RemoteReadJson::pageRequest(r.payload,&p)||!r.payload.value("text").isString()||r.payload.value("text").toString().size()>RemoteReadDto::MaximumTextLength){invalid(r,std::move(c),"The Collection search criteria are invalid.");return;}CollectionSearchCriteria q;q.workspaceId=wid;q.searchText=r.payload.value("text").toString();q.limit=p.pageSize;q.offset=(p.page-1)*p.pageSize;m_executor->searchCollection(q,this,[r,c,p](const CollectionApplicationService::Page&result){QJsonArray a;for(const auto&x:result.rows){RemoteReadDto::CollectionSummary v;v.collectionItemId=x.item.id;v.workspaceId=x.item.workspaceId;v.type=collectionItemTypeToString(x.item.type);if(x.item.type==CollectionItemType::Set)v.setNumber=x.displayReference;else if(x.item.type==CollectionItemType::Minifig)v.minifigNumber=x.displayReference;v.titleFallback=x.displayName;v.state=collectionItemStateToString(x.item.state);v.condition=collectionItemConditionToString(x.item.condition);v.completeness=collectionItemCompletenessToString(x.item.completeness);v.storageId=x.item.storageLocationId;v.storagePath=x.locationName;v.nickname=x.item.nickname;v.active=x.item.isActive;a.append(RemoteReadJson::toJson(v));}c(BrickSuiteProtocol::response(r,{{"rows",a},{"page",p.page},{"pageSize",p.pageSize},{"totalRows",result.total}}));},[r,c](const QString&e){failed(r,c,e);});});
 d.registerAsyncOperation("collection.get",true,[this](const auto&r,Completion c){int id=0;if(r.payload.size()!=1||!positiveId(r.payload,"collectionItemId",&id)){invalid(r,std::move(c),"A positive collectionItemId is required.");return;}m_executor->getCollection(id,this,[r,c](const std::optional<CollectionSearchResult>&x){if(!x){c(BrickSuiteProtocol::errorResponse(r,"NOT_FOUND","The requested Collection item was not found."));return;}RemoteReadDto::CollectionDetail v;v.collectionItemId=x->item.id;v.workspaceId=x->item.workspaceId;v.type=collectionItemTypeToString(x->item.type);if(x->item.type==CollectionItemType::Set)v.setNumber=x->displayReference;else if(x->item.type==CollectionItemType::Minifig)v.minifigNumber=x->displayReference;v.titleFallback=x->displayName;v.state=collectionItemStateToString(x->item.state);v.condition=collectionItemConditionToString(x->item.condition);v.completeness=collectionItemCompletenessToString(x->item.completeness);v.storageId=x->item.storageLocationId;v.storagePath=x->locationName;v.nickname=x->item.nickname;v.active=x->item.isActive;v.notes=x->item.notes;v.createdUtc=x->item.createdUtc;v.modifiedUtc=x->item.modifiedUtc;c(BrickSuiteProtocol::response(r,{{"item",RemoteReadJson::toJson(v)}}));},[r,c](const QString&e){failed(r,c,e);});});
 d.registerAsyncOperation("partReference.customizations",true,[this](const auto&r,Completion c){if(!r.payload.isEmpty()){invalid(r,std::move(c),"partReference.customizations does not accept payload fields.");return;}PartReferenceManifest m;QString e;if(!m.load(&e)){failed(r,std::move(c),e);return;}m_executor->effectivePartReference(m,this,[r,c](const QList<PartReferenceEntry>&rows,const QString&e){if(!e.isEmpty()){failed(r,c,e);return;}QJsonArray a;for(const auto&x:rows){if(x.origin!=PartReferenceEntry::Origin::User)continue;a.append(RemoteReadJson::toJson({x.userEntryId,x.partNumber,x.partName,x.catalog,x.section,x.displayOrder,x.representativeFor,x.notes}));}c(BrickSuiteProtocol::response(r,{{"rows",a}}));},[r,c](const QString&e2){failed(r,c,e2);});});
}
