include(FetchContent)
set(LIB3MF_BUILD_SHARED OFF CACHE BOOL "Build lib3mf statically" FORCE)
set(LIB3MF_TESTS OFF CACHE BOOL "Disable lib3mf tests" FORCE)
set(USE_INCLUDED_ZLIB ON CACHE BOOL "Use pinned lib3mf zlib" FORCE)
set(USE_INCLUDED_LIBZIP ON CACHE BOOL "Use pinned lib3mf libzip" FORCE)
set(USE_INCLUDED_SSL ON CACHE BOOL "Use pinned lib3mf SSL implementation" FORCE)
FetchContent_Declare(lib3mf
    GIT_REPOSITORY https://github.com/3MFConsortium/lib3mf.git
    GIT_TAG 64bb454d1fcb53effa57d3cef752a10d740d41a2
    GIT_SHALLOW FALSE
    GIT_SUBMODULES_RECURSE TRUE)
FetchContent_MakeAvailable(lib3mf)
add_library(BrickSuiteLib3mf INTERFACE)
target_link_libraries(BrickSuiteLib3mf INTERFACE lib3mf)
target_include_directories(BrickSuiteLib3mf INTERFACE "${lib3mf_SOURCE_DIR}/Autogenerated/Bindings/Cpp")
add_library(BrickSuite::Lib3mf ALIAS BrickSuiteLib3mf)
set(_license_dir "${CMAKE_BINARY_DIR}/deployment/licenses/lib3mf")
file(MAKE_DIRECTORY "${_license_dir}")
configure_file("${lib3mf_SOURCE_DIR}/LICENSE" "${_license_dir}/LICENSE" COPYONLY)
