#include "FitCalibrationDialog.h"
#include "../../services/geometry/ThreeMfWriter.h"
#include "../../services/geometry/fit/RoundTechnicCalibrationArtifact.h"
#include "../common/SessionFileDialogDirectoryService.h"
#include <QComboBox>
#include <QDialogButtonBox>
#include <QDoubleSpinBox>
#include <QFile>
#include <QFileDialog>
#include <QFormLayout>
#include <QGroupBox>
#include <QHBoxLayout>
#include <QHeaderView>
#include <QInputDialog>
#include <QJsonDocument>
#include <QLabel>
#include <QLineEdit>
#include <QMessageBox>
#include <QPushButton>
#include <QSaveFile>
#include <QSpinBox>
#include <QTabWidget>
#include <QTableWidget>
#include <QVBoxLayout>
#include <algorithm>
using namespace PrintGeometry;
namespace {
QString resultText(FitObservation v){switch(v){case FitObservation::TooTight:return "Too Tight";case FitObservation::Acceptable:return "Acceptable";case FitObservation::Preferred:return "Preferred";case FitObservation::TooLoose:return "Too Loose";case FitObservation::UnableToEvaluate:return "Unable to Evaluate";default:return "Unevaluated";}}
QTableWidget* makeTable(QWidget*p){auto*t=new QTableWidget(p);t->setColumnCount(6);t->setHorizontalHeaderLabels({"Candidate","Correction (mm)","Diameter (mm)","Observations","Last Result","Preferred"});t->horizontalHeader()->setSectionResizeMode(QHeaderView::Stretch);t->setSelectionBehavior(QAbstractItemView::SelectRows);return t;}
QString stagePath(const QString&model){return model.endsWith(".3mf",Qt::CaseInsensitive)?model.left(model.size()-4)+"-session.json":model+"-session.json";}
}
FitCalibrationDialog::FitCalibrationDialog(QWidget*p):QDialog(p){setWindowTitle("LEGO Fit Calibration");resize(920,700);auto*root=new QVBoxLayout(this);auto*files=new QHBoxLayout;auto*load=new QPushButton("Load Session...",this);m_save=new QPushButton("Save",this);auto*saveAs=new QPushButton("Save As...",this);files->addWidget(load);files->addWidget(m_save);files->addWidget(saveAs);files->addStretch();root->addLayout(files);
auto*process=new QGroupBox("Actual Print Process",this);auto*form=new QFormLayout(process);m_printer=new QLineEdit(process);m_material=new QLineEdit(process);m_profile=new QLineEdit(process);m_nozzle=new QDoubleSpinBox(process);m_nozzle->setRange(.1,2);m_nozzle->setDecimals(2);m_nozzle->setValue(.4);m_nozzle->setSuffix(" mm");m_layer=new QDoubleSpinBox(process);m_layer->setRange(.01,2);m_layer->setDecimals(3);m_layer->setValue(.2);m_layer->setSuffix(" mm");m_orientation=new QComboBox(process);m_orientation->addItem("Select actual printed orientation",int(FitPrintedOrientation::Unknown));m_orientation->addItem("Feature axis parallel to build plate",int(FitPrintedOrientation::FeatureAxisParallelToBuildPlate));m_orientation->addItem("Feature axis perpendicular to build plate",int(FitPrintedOrientation::FeatureAxisPerpendicularToBuildPlate));m_orientation->addItem("Other / unsupported",int(FitPrintedOrientation::OtherUnsupported));m_orientationNotes=new QLineEdit(process);m_compensationNotes=new QLineEdit(process);form->addRow("Printer:",m_printer);form->addRow("Material:",m_material);form->addRow("Nozzle:",m_nozzle);form->addRow("Process/profile:",m_profile);form->addRow("Layer height:",m_layer);form->addRow("Actual orientation:",m_orientation);form->addRow("Orientation notes:",m_orientationNotes);form->addRow("Slicer compensation:",m_compensationNotes);root->addWidget(process);
m_tabs=new QTabWidget(this);auto*coarse=new QWidget(m_tabs);auto*coarseLayout=new QVBoxLayout(coarse);m_coarseContext=new QLabel(coarse);m_coarseTable=makeTable(coarse);coarseLayout->addWidget(m_coarseContext);coarseLayout->addWidget(m_coarseTable);auto*fine=new QWidget(m_tabs);auto*fineLayout=new QVBoxLayout(fine);m_fineContext=new QLabel(fine);m_fineTable=makeTable(fine);fineLayout->addWidget(m_fineContext);fineLayout->addWidget(m_fineTable);m_tabs->addTab(coarse,"Coarse Search");m_tabs->addTab(fine,"Fine Search / Verification");root->addWidget(m_tabs,1);
auto*entry=new QHBoxLayout;m_result=new QComboBox(this);for(auto v:{FitObservation::TooTight,FitObservation::Acceptable,FitObservation::Preferred,FitObservation::TooLoose,FitObservation::UnableToEvaluate})m_result->addItem(resultText(v),int(v));m_repeat=new QSpinBox(this);m_repeat->setRange(1,99);m_measured=new QDoubleSpinBox(this);m_measured->setRange(0,99);m_measured->setDecimals(3);m_measured->setSpecialValueText("Not measured");m_notes=new QLineEdit(this);m_notes->setPlaceholderText("Observation notes");auto*add=new QPushButton("Add Observation",this);auto*preferred=new QPushButton("Select Preferred",this);m_generate=new QPushButton("Generate Fine Search...",this);m_verify=new QPushButton("Mark Verified",this);entry->addWidget(m_result);entry->addWidget(m_repeat);entry->addWidget(m_measured);entry->addWidget(m_notes,1);entry->addWidget(add);entry->addWidget(preferred);entry->addWidget(m_generate);entry->addWidget(m_verify);root->addLayout(entry);
auto*bottom=new QHBoxLayout;m_guidance=new QLabel(this);m_guidance->setWordWrap(true);m_guidance->setSizePolicy(QSizePolicy::Expanding,QSizePolicy::Preferred);auto*buttons=new QDialogButtonBox(QDialogButtonBox::Close,this);bottom->addWidget(m_guidance,1);bottom->addWidget(buttons);root->addLayout(bottom);
connect(buttons,&QDialogButtonBox::rejected,this,&QDialog::reject);connect(load,&QPushButton::clicked,this,&FitCalibrationDialog::loadSession);connect(m_save,&QPushButton::clicked,this,[this]{saveSession();});connect(saveAs,&QPushButton::clicked,this,[this]{const auto old=m_path;m_path.clear();if(!saveSession())m_path=old;});connect(add,&QPushButton::clicked,this,&FitCalibrationDialog::addObservation);connect(preferred,&QPushButton::clicked,this,&FitCalibrationDialog::selectPreferred);connect(m_generate,&QPushButton::clicked,this,&FitCalibrationDialog::generateFineSearch);connect(m_verify,&QPushButton::clicked,this,&FitCalibrationDialog::markVerified);connect(m_tabs,&QTabWidget::currentChanged,this,[this]{refresh();});auto processChanged=[this]{readProcess();if(!m_loading){m_dirty=true;m_savedConfirmation=false;}updateGuidance();};connect(m_printer,&QLineEdit::textChanged,this,processChanged);connect(m_material,&QLineEdit::textChanged,this,processChanged);connect(m_profile,&QLineEdit::textChanged,this,processChanged);connect(m_orientationNotes,&QLineEdit::textChanged,this,processChanged);connect(m_compensationNotes,&QLineEdit::textChanged,this,processChanged);connect(m_nozzle,qOverload<double>(&QDoubleSpinBox::valueChanged),this,[processChanged](double){processChanged();});connect(m_layer,qOverload<double>(&QDoubleSpinBox::valueChanged),this,[processChanged](double){processChanged();});connect(m_orientation,qOverload<int>(&QComboBox::currentIndexChanged),this,[processChanged](int){processChanged();});refresh();}
FitCalibrationExperiment* FitCalibrationDialog::activeExperiment(){if(m_tabs->currentIndex()==0)return m_session.hasCoarseExperiment?&m_session.coarseExperiment:nullptr;return m_session.hasFineExperiment?&m_session.fineExperiment:nullptr;}
QTableWidget* FitCalibrationDialog::activeTable()const{return m_tabs->currentIndex()==0?m_coarseTable:m_fineTable;}
void FitCalibrationDialog::readProcess(){m_session.process.printerIdentity=m_printer->text().trimmed();m_session.process.materialIdentity=m_material->text().trimmed();m_session.process.profileName=m_profile->text().trimmed();m_session.process.hasNozzleDiameter=true;m_session.process.nozzleDiameterMillimetres=m_nozzle->value();m_session.process.hasLayerHeight=true;m_session.process.layerHeightMillimetres=m_layer->value();m_session.process.actualPrintedOrientation=FitPrintedOrientation(m_orientation->currentData().toInt());m_session.process.orientationNotes=m_orientationNotes->text();m_session.process.dimensionalCompensationNotes=m_compensationNotes->text();if(m_session.hasCoarseExperiment)m_session.coarseExperiment.process=m_session.process;if(m_session.hasFineExperiment)m_session.fineExperiment.process=m_session.process;}
void FitCalibrationDialog::refreshTable(QTableWidget*t,const FitCalibrationExperiment*e){t->setRowCount(e?e->candidates.size():0);if(!e)return;for(int r=0;r<e->candidates.size();++r){const auto&c=e->candidates[r];t->setItem(r,0,new QTableWidgetItem(QString::number(c.index)));t->setItem(r,1,new QTableWidgetItem(QString::number(c.diameterCorrectionMillimetres,'f',3)));t->setItem(r,2,new QTableWidgetItem(QString::number(c.functionalDiameterMillimetres,'f',3)));t->setItem(r,3,new QTableWidgetItem(QString::number(c.observations.size())));t->setItem(r,4,new QTableWidgetItem(c.observations.isEmpty()?QString():resultText(c.observations.back().result)));t->setItem(r,5,new QTableWidgetItem(c.index==e->preferredCandidateIndex?"Yes":""));}}
void FitCalibrationDialog::refresh(){refreshTable(m_coarseTable,m_session.hasCoarseExperiment?&m_session.coarseExperiment:nullptr);refreshTable(m_fineTable,m_session.hasFineExperiment?&m_session.fineExperiment:nullptr);m_tabs->setTabEnabled(0,m_session.hasCoarseExperiment);m_tabs->setTabEnabled(1,m_session.hasFineExperiment);m_coarseContext->setText(m_session.hasCoarseExperiment?QStringLiteral("Artifact: %1").arg(m_session.coarseExperiment.artifactIdentity):QStringLiteral("No coarse search is present in this legacy session."));m_fineContext->setText(m_session.hasFineExperiment?QStringLiteral("Artifact: %1 — Parent: %2 — Center: %3 mm").arg(m_session.fineExperiment.artifactIdentity,m_session.fineExperiment.parentArtifactIdentity).arg(m_session.fineExperiment.centerDiameterCorrectionMillimetres,0,'f',3):QStringLiteral("Generate a fine search from a selected coarse candidate."));m_save->setEnabled(m_session.hasCoarseExperiment||m_session.hasFineExperiment);m_generate->setEnabled(m_tabs->currentIndex()==0&&m_session.hasCoarseExperiment);auto*e=activeExperiment();bool ready=false;if(e&&m_tabs->currentIndex()==1&&e->state!=FitEvidenceState::Verified){auto copy=*e;QString ignored;ready=FitCalibrationEvidencePolicy::markVerified(&copy,&ignored);}m_verify->setEnabled(ready);m_verify->setText(e&&e->state==FitEvidenceState::Verified?QStringLiteral("Verified"):QStringLiteral("Mark Verified"));updateGuidance();}
void FitCalibrationDialog::updateGuidance(){const auto*e=activeExperiment();QString text=e?FitCalibrationEvidencePolicy::guidanceText(*e):QStringLiteral("Load a calibration session to begin.");if(e&&e->state==FitEvidenceState::Verified&&e->preferredCandidateIndex>0){const auto it=std::find_if(e->candidates.cbegin(),e->candidates.cend(),[e](const auto&c){return c.index==e->preferredCandidateIndex;});if(it!=e->candidates.cend()){if(m_savedConfirmation&&!m_dirty)text=QStringLiteral("Verified calibration saved: %1 mm.").arg(it->diameterCorrectionMillimetres,0,'f',3);else if(!m_dirty)text=QStringLiteral("Verified calibration loaded: %1 mm.").arg(it->diameterCorrectionMillimetres,0,'f',3);}}else if(m_savedConfirmation&&!m_dirty)text=QStringLiteral("Calibration session saved successfully.");m_guidance->setText(text);m_guidance->setToolTip(text);}
void FitCalibrationDialog::showSession(const FitCalibrationSession&s,const QString&path){m_loading=true;m_session=s;m_path=path;m_dirty=false;m_savedConfirmation=false;m_printer->setText(s.process.printerIdentity);m_material->setText(s.process.materialIdentity);m_profile->setText(s.process.profileName);if(s.process.hasNozzleDiameter)m_nozzle->setValue(s.process.nozzleDiameterMillimetres);if(s.process.hasLayerHeight)m_layer->setValue(s.process.layerHeightMillimetres);m_orientation->setCurrentIndex(m_orientation->findData(int(s.process.actualPrintedOrientation)));m_orientationNotes->setText(s.process.orientationNotes);m_compensationNotes->setText(s.process.dimensionalCompensationNotes);m_tabs->setCurrentIndex(s.hasCoarseExperiment?0:1);m_loading=false;refresh();}
bool FitCalibrationDialog::openSession(const QString&path){QFile f(path);if(!f.open(QIODevice::ReadOnly)){QMessageBox::warning(this,"Calibration",f.errorString());return false;}FitCalibrationSession s;QString error;if(!FitCalibrationSessionJson::fromJson(QJsonDocument::fromJson(f.readAll()).object(),&s,&error)){QMessageBox::warning(this,"Calibration",error);return false;}showSession(s,path);return true;}
void FitCalibrationDialog::loadSession(){auto&dirs=SessionFileDialogDirectoryService::instance();const auto path=QFileDialog::getOpenFileName(this,"Open Calibration Session",dirs.initialDirectory(FileDialogDirectoryCategory::OpenImport),"Calibration JSON (*.json)");if(path.isEmpty())return;dirs.rememberSelectedFile(FileDialogDirectoryCategory::OpenImport,path);openSession(path);}
bool FitCalibrationDialog::writeSession(const QString&path){QSaveFile f(path);if(!f.open(QIODevice::WriteOnly)||f.write(QJsonDocument(FitCalibrationSessionJson::toJson(m_session)).toJson(QJsonDocument::Indented))<0||!f.commit()){QMessageBox::warning(this,"Calibration","The calibration session could not be saved.");return false;}m_dirty=false;m_savedConfirmation=true;updateGuidance();return true;}
bool FitCalibrationDialog::saveSession(){if(!m_session.hasCoarseExperiment&&!m_session.hasFineExperiment)return false;readProcess();if(m_path.isEmpty()){auto&dirs=SessionFileDialogDirectoryService::instance();const QString identity=m_session.sessionIdentity.isEmpty()?QStringLiteral("BrickSuite-fit-calibration"):m_session.sessionIdentity;m_path=QFileDialog::getSaveFileName(this,"Save Calibration Session",dirs.initialFilePath(FileDialogDirectoryCategory::SaveExport,identity+"-session.json"),"Calibration JSON (*.json)");if(!m_path.isEmpty())dirs.rememberSelectedFile(FileDialogDirectoryCategory::SaveExport,m_path);}return !m_path.isEmpty()&&writeSession(m_path);}
void FitCalibrationDialog::addObservation(){auto*e=activeExperiment();auto*t=activeTable();const int row=t->currentRow();if(!e||row<0){QMessageBox::information(this,"Calibration","Select a candidate first.");return;}FitCalibrationObservation o;o.result=FitObservation(m_result->currentData().toInt());o.repeatNumber=m_repeat->value();o.hasMeasuredDiameter=m_measured->value()>0;o.measuredDiameterMillimetres=m_measured->value();o.notes=m_notes->text();o.performedUtc=QDateTime::currentDateTimeUtc();QString error;if(!FitCalibrationEvidencePolicy::addObservation(e,e->candidates[row].index,o,&error))QMessageBox::warning(this,"Calibration",error);else{m_dirty=true;m_savedConfirmation=false;refresh();}}
void FitCalibrationDialog::selectPreferred(){auto*e=activeExperiment();auto*t=activeTable();const int row=t->currentRow();QString error;if(!e||row<0||!FitCalibrationEvidencePolicy::selectPreferredCandidate(e,row<0||!e?0:e->candidates[row].index,&error))QMessageBox::warning(this,"Calibration",error.isEmpty()?"Select a candidate first.":error);else{m_dirty=true;m_savedConfirmation=false;refresh();}}
void FitCalibrationDialog::markVerified(){auto*e=activeExperiment();readProcess();QString error;if(!e||e->state==FitEvidenceState::Verified||!FitCalibrationEvidencePolicy::markVerified(e,&error)){if(e&&e->state==FitEvidenceState::Verified)return;QMessageBox::warning(this,"Calibration",error.isEmpty()?"Open the fine-search stage first.":error);}else{m_dirty=true;m_savedConfirmation=false;refresh();}}
void FitCalibrationDialog::generateFineSearch(){if(!m_session.hasCoarseExperiment)return;auto&coarse=m_session.coarseExperiment;if(!coarse.hasRegenerationPrototype||coarse.preferredCandidateIndex<=0){QMessageBox::warning(this,"Calibration","Select a preferred coarse candidate first.");return;}const auto selected=std::find_if(coarse.candidates.cbegin(),coarse.candidates.cend(),[&](const auto&c){return c.index==coarse.preferredCandidateIndex;});if(selected==coarse.candidates.cend())return;bool ok=false;const double spacing=QInputDialog::getDouble(this,"Fine Search","Candidate spacing (mm):",.025,.001,1,3,&ok);if(!ok)return;const int count=QInputDialog::getInt(this,"Fine Search","Odd candidate count:",5,3,9,2,&ok);if(!ok)return;const QString identity=QInputDialog::getText(this,"Fine Search","Versioned artifact identity:",QLineEdit::Normal,coarse.artifactIdentity+"-verification-v2",&ok).trimmed();if(!ok||identity.isEmpty())return;readProcess();auto&dirs=SessionFileDialogDirectoryService::instance();const QString path=QFileDialog::getSaveFileName(this,"Save Fine-Search 3MF",dirs.initialFilePath(FileDialogDirectoryCategory::SaveExport,identity+".3mf"),"3MF models (*.3mf)");if(path.isEmpty())return;dirs.rememberSelectedFile(FileDialogDirectoryCategory::SaveExport,path);RoundTechnicCalibrationArtifactDefinition d;d.artifactIdentity=identity;d.parentArtifactIdentity=coarse.artifactIdentity;d.centerDiameterCorrectionMillimetres=selected->diameterCorrectionMillimetres;d.candidateSpacingMillimetres=spacing;d.candidateCount=count;const auto artifact=RoundTechnicCalibrationArtifact::generate(coarse.regenerationPrototype,d);if(!artifact.ok){QMessageBox::warning(this,"Calibration",artifact.diagnostic);return;}ThreeMfWriter::Options options;options.objectName=identity;options.partIdentity=identity;options.modelColor=QColor("#0055BF");QString error;if(!ThreeMfWriter::write(artifact.mesh,path,options,&error)){QMessageBox::warning(this,"Calibration",error);return;}auto fine=RoundTechnicCalibrationArtifact::observationTemplate(artifact,d);fine.process=m_session.process;m_session.hasFineExperiment=true;m_session.fineExperiment=fine;if(m_session.sessionIdentity.isEmpty())m_session.sessionIdentity=coarse.artifactIdentity;m_dirty=true;m_savedConfirmation=false;if(!saveSession())return;m_tabs->setCurrentIndex(1);refresh();QMessageBox::information(this,"Fine Search Generated",QStringLiteral("The fine-search 3MF was saved. Its empty candidate evidence is now available on the Fine Search / Verification tab in this session."));}
